// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/blog.proto" (package "blog", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { BlogService } from "./blog";
import type { BlogGroupResponseWrapped } from "./blog";
import type { BlogGroupDataSourceResponse } from "./blog";
import type { GetBySlugPagedRequest } from "./common";
import type { BlogResponseWrapped } from "./blog";
import type { GetBySlugRequest } from "./common";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { BlogDataSourceResponse } from "./blog";
import type { CommonQuery } from "./common";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service blog.BlogService
 */
export interface IBlogServiceClient {
    /**
     * @generated from protobuf rpc: GetBlogsByQuery
     */
    getBlogsByQuery(input: CommonQuery, options?: RpcOptions): UnaryCall<CommonQuery, BlogDataSourceResponse>;
    /**
     * @generated from protobuf rpc: GetBlogDetail
     */
    getBlogDetail(input: GetBySlugRequest, options?: RpcOptions): UnaryCall<GetBySlugRequest, BlogResponseWrapped>;
    /**
     * @generated from protobuf rpc: GetBlogsByBlogGroupSlug
     */
    getBlogsByBlogGroupSlug(input: GetBySlugPagedRequest, options?: RpcOptions): UnaryCall<GetBySlugPagedRequest, BlogDataSourceResponse>;
    /**
     * @generated from protobuf rpc: GetBlogGroupsByQuery
     */
    getBlogGroupsByQuery(input: CommonQuery, options?: RpcOptions): UnaryCall<CommonQuery, BlogGroupDataSourceResponse>;
    /**
     * @generated from protobuf rpc: GetBlogGroupsBySlug
     */
    getBlogGroupsBySlug(input: GetBySlugRequest, options?: RpcOptions): UnaryCall<GetBySlugRequest, BlogGroupResponseWrapped>;
}
/**
 * @generated from protobuf service blog.BlogService
 */
export class BlogServiceClient implements IBlogServiceClient, ServiceInfo {
    typeName = BlogService.typeName;
    methods = BlogService.methods;
    options = BlogService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetBlogsByQuery
     */
    getBlogsByQuery(input: CommonQuery, options?: RpcOptions): UnaryCall<CommonQuery, BlogDataSourceResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CommonQuery, BlogDataSourceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBlogDetail
     */
    getBlogDetail(input: GetBySlugRequest, options?: RpcOptions): UnaryCall<GetBySlugRequest, BlogResponseWrapped> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBySlugRequest, BlogResponseWrapped>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBlogsByBlogGroupSlug
     */
    getBlogsByBlogGroupSlug(input: GetBySlugPagedRequest, options?: RpcOptions): UnaryCall<GetBySlugPagedRequest, BlogDataSourceResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBySlugPagedRequest, BlogDataSourceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBlogGroupsByQuery
     */
    getBlogGroupsByQuery(input: CommonQuery, options?: RpcOptions): UnaryCall<CommonQuery, BlogGroupDataSourceResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<CommonQuery, BlogGroupDataSourceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBlogGroupsBySlug
     */
    getBlogGroupsBySlug(input: GetBySlugRequest, options?: RpcOptions): UnaryCall<GetBySlugRequest, BlogGroupResponseWrapped> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBySlugRequest, BlogGroupResponseWrapped>("unary", this._transport, method, opt, input);
    }
}
