// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/blog.proto" (package "blog", syntax proto3)
// tslint:disable
import { GetBySlugPagedRequest } from "./common";
import { GetBySlugRequest } from "./common";
import { CommonQuery } from "./common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { CommonDataSourceMeta } from "./common";
import { CommonCriteria } from "./common";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message blog.BlogResponse
 */
export interface BlogResponse {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string slug = 3
     */
    slug: string;
    /**
     * @generated from protobuf field: string img_url = 4
     */
    imgUrl: string;
    /**
     * @generated from protobuf field: string short_description = 5
     */
    shortDescription: string;
    /**
     * @generated from protobuf field: string content = 6
     */
    content: string;
    /**
     * @generated from protobuf field: string author = 7
     */
    author: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 8
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 9
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: repeated string tags = 10
     */
    tags: string[];
    /**
     * @generated from protobuf field: string status = 11
     */
    status: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp published_at = 12
     */
    publishedAt?: Timestamp;
    /**
     * @generated from protobuf field: int32 views = 13
     */
    views: number;
    /**
     * @generated from protobuf field: string image_alt = 14
     */
    imageAlt: string;
    /**
     * @generated from protobuf field: string blog_group_id = 18
     */
    blogGroupId: string;
    /**
     * @generated from protobuf field: string type = 19
     */
    type: string;
    /**
     * @generated from protobuf field: string template = 20
     */
    template: string;
    /**
     * @generated from protobuf field: string org_id = 21
     */
    orgId: string;
    /**
     * @generated from protobuf field: string created_by = 22
     */
    createdBy: string;
    /**
     * @generated from protobuf field: string updated_by = 23
     */
    updatedBy: string;
    /**
     * @generated from protobuf field: map<string, string> extend_object = 24
     */
    extendObject: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: string package_index = 25
     */
    packageIndex: string;
}
/**
 * @generated from protobuf message blog.BlogGroupResponse
 */
export interface BlogGroupResponse {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string url = 3
     */
    url: string;
    /**
     * @generated from protobuf field: string description = 4
     */
    description: string;
    /**
     * @generated from protobuf field: string content = 5
     */
    content: string;
    /**
     * @generated from protobuf field: string status = 6
     */
    status: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 7
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 8
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: string org_id = 9
     */
    orgId: string;
    /**
     * @generated from protobuf field: repeated blog.BlogResponse blogs = 10
     */
    blogs: BlogResponse[];
    /**
     * @generated from protobuf field: string created_by = 11
     */
    createdBy: string;
    /**
     * @generated from protobuf field: string updated_by = 12
     */
    updatedBy: string;
    /**
     * @generated from protobuf field: map<string, string> extend_object = 13
     */
    extendObject: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: repeated string blog_ids = 14
     */
    blogIds: string[];
    /**
     * @generated from protobuf field: string group_by = 15
     */
    groupBy: string;
    /**
     * @generated from protobuf field: string operator = 16
     */
    operator: string;
    /**
     * @generated from protobuf field: repeated common.CommonCriteria criteria = 17
     */
    criteria: CommonCriteria[];
    /**
     * @generated from protobuf field: string package_index = 18
     */
    packageIndex: string;
}
/**
 * @generated from protobuf message blog.BlogDataSourceResponse
 */
export interface BlogDataSourceResponse {
    /**
     * @generated from protobuf field: common.CommonDataSourceMeta meta = 1
     */
    meta?: CommonDataSourceMeta;
    /**
     * @generated from protobuf field: repeated blog.BlogResponse data = 2
     */
    data: BlogResponse[];
}
/**
 * @generated from protobuf message blog.BlogGroupDataSourceResponse
 */
export interface BlogGroupDataSourceResponse {
    /**
     * @generated from protobuf field: common.CommonDataSourceMeta meta = 1
     */
    meta?: CommonDataSourceMeta;
    /**
     * @generated from protobuf field: repeated blog.BlogGroupResponse data = 2
     */
    data: BlogGroupResponse[];
}
/**
 * @generated from protobuf message blog.BlogResponseWrapped
 */
export interface BlogResponseWrapped {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: blog.BlogResponse data = 3
     */
    data?: BlogResponse;
}
/**
 * @generated from protobuf message blog.BlogGroupResponseWrapped
 */
export interface BlogGroupResponseWrapped {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: blog.BlogGroupResponse data = 3
     */
    data?: BlogGroupResponse;
}
// @generated message type with reflection information, may provide speed optimized methods
class BlogResponse$Type extends MessageType<BlogResponse> {
    constructor() {
        super("blog.BlogResponse", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "img_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "short_description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "author", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 9, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 10, name: "tags", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "published_at", kind: "message", T: () => Timestamp },
            { no: 13, name: "views", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 14, name: "image_alt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "blog_group_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 20, name: "template", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 21, name: "org_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 22, name: "created_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 23, name: "updated_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 24, name: "extend_object", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 25, name: "package_index", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<BlogResponse>): BlogResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.title = "";
        message.slug = "";
        message.imgUrl = "";
        message.shortDescription = "";
        message.content = "";
        message.author = "";
        message.tags = [];
        message.status = "";
        message.views = 0;
        message.imageAlt = "";
        message.blogGroupId = "";
        message.type = "";
        message.template = "";
        message.orgId = "";
        message.createdBy = "";
        message.updatedBy = "";
        message.extendObject = {};
        message.packageIndex = "";
        if (value !== undefined)
            reflectionMergePartial<BlogResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlogResponse): BlogResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string slug */ 3:
                    message.slug = reader.string();
                    break;
                case /* string img_url */ 4:
                    message.imgUrl = reader.string();
                    break;
                case /* string short_description */ 5:
                    message.shortDescription = reader.string();
                    break;
                case /* string content */ 6:
                    message.content = reader.string();
                    break;
                case /* string author */ 7:
                    message.author = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 8:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 9:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* repeated string tags */ 10:
                    message.tags.push(reader.string());
                    break;
                case /* string status */ 11:
                    message.status = reader.string();
                    break;
                case /* google.protobuf.Timestamp published_at */ 12:
                    message.publishedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.publishedAt);
                    break;
                case /* int32 views */ 13:
                    message.views = reader.int32();
                    break;
                case /* string image_alt */ 14:
                    message.imageAlt = reader.string();
                    break;
                case /* string blog_group_id */ 18:
                    message.blogGroupId = reader.string();
                    break;
                case /* string type */ 19:
                    message.type = reader.string();
                    break;
                case /* string template */ 20:
                    message.template = reader.string();
                    break;
                case /* string org_id */ 21:
                    message.orgId = reader.string();
                    break;
                case /* string created_by */ 22:
                    message.createdBy = reader.string();
                    break;
                case /* string updated_by */ 23:
                    message.updatedBy = reader.string();
                    break;
                case /* map<string, string> extend_object */ 24:
                    this.binaryReadMap24(message.extendObject, reader, options);
                    break;
                case /* string package_index */ 25:
                    message.packageIndex = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap24(map: BlogResponse["extendObject"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof BlogResponse["extendObject"] | undefined, val: BlogResponse["extendObject"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for blog.BlogResponse.extend_object");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: BlogResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string slug = 3; */
        if (message.slug !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.slug);
        /* string img_url = 4; */
        if (message.imgUrl !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.imgUrl);
        /* string short_description = 5; */
        if (message.shortDescription !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.shortDescription);
        /* string content = 6; */
        if (message.content !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.content);
        /* string author = 7; */
        if (message.author !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.author);
        /* google.protobuf.Timestamp created_at = 8; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 9; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* repeated string tags = 10; */
        for (let i = 0; i < message.tags.length; i++)
            writer.tag(10, WireType.LengthDelimited).string(message.tags[i]);
        /* string status = 11; */
        if (message.status !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.status);
        /* google.protobuf.Timestamp published_at = 12; */
        if (message.publishedAt)
            Timestamp.internalBinaryWrite(message.publishedAt, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* int32 views = 13; */
        if (message.views !== 0)
            writer.tag(13, WireType.Varint).int32(message.views);
        /* string image_alt = 14; */
        if (message.imageAlt !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.imageAlt);
        /* string blog_group_id = 18; */
        if (message.blogGroupId !== "")
            writer.tag(18, WireType.LengthDelimited).string(message.blogGroupId);
        /* string type = 19; */
        if (message.type !== "")
            writer.tag(19, WireType.LengthDelimited).string(message.type);
        /* string template = 20; */
        if (message.template !== "")
            writer.tag(20, WireType.LengthDelimited).string(message.template);
        /* string org_id = 21; */
        if (message.orgId !== "")
            writer.tag(21, WireType.LengthDelimited).string(message.orgId);
        /* string created_by = 22; */
        if (message.createdBy !== "")
            writer.tag(22, WireType.LengthDelimited).string(message.createdBy);
        /* string updated_by = 23; */
        if (message.updatedBy !== "")
            writer.tag(23, WireType.LengthDelimited).string(message.updatedBy);
        /* map<string, string> extend_object = 24; */
        for (let k of globalThis.Object.keys(message.extendObject))
            writer.tag(24, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.extendObject[k]).join();
        /* string package_index = 25; */
        if (message.packageIndex !== "")
            writer.tag(25, WireType.LengthDelimited).string(message.packageIndex);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message blog.BlogResponse
 */
export const BlogResponse = new BlogResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BlogGroupResponse$Type extends MessageType<BlogGroupResponse> {
    constructor() {
        super("blog.BlogGroupResponse", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 8, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 9, name: "org_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "blogs", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => BlogResponse },
            { no: 11, name: "created_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "updated_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "extend_object", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 14, name: "blog_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "group_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "operator", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "criteria", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CommonCriteria },
            { no: 18, name: "package_index", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<BlogGroupResponse>): BlogGroupResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.url = "";
        message.description = "";
        message.content = "";
        message.status = "";
        message.orgId = "";
        message.blogs = [];
        message.createdBy = "";
        message.updatedBy = "";
        message.extendObject = {};
        message.blogIds = [];
        message.groupBy = "";
        message.operator = "";
        message.criteria = [];
        message.packageIndex = "";
        if (value !== undefined)
            reflectionMergePartial<BlogGroupResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlogGroupResponse): BlogGroupResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string url */ 3:
                    message.url = reader.string();
                    break;
                case /* string description */ 4:
                    message.description = reader.string();
                    break;
                case /* string content */ 5:
                    message.content = reader.string();
                    break;
                case /* string status */ 6:
                    message.status = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 7:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 8:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* string org_id */ 9:
                    message.orgId = reader.string();
                    break;
                case /* repeated blog.BlogResponse blogs */ 10:
                    message.blogs.push(BlogResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string created_by */ 11:
                    message.createdBy = reader.string();
                    break;
                case /* string updated_by */ 12:
                    message.updatedBy = reader.string();
                    break;
                case /* map<string, string> extend_object */ 13:
                    this.binaryReadMap13(message.extendObject, reader, options);
                    break;
                case /* repeated string blog_ids */ 14:
                    message.blogIds.push(reader.string());
                    break;
                case /* string group_by */ 15:
                    message.groupBy = reader.string();
                    break;
                case /* string operator */ 16:
                    message.operator = reader.string();
                    break;
                case /* repeated common.CommonCriteria criteria */ 17:
                    message.criteria.push(CommonCriteria.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string package_index */ 18:
                    message.packageIndex = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap13(map: BlogGroupResponse["extendObject"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof BlogGroupResponse["extendObject"] | undefined, val: BlogGroupResponse["extendObject"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for blog.BlogGroupResponse.extend_object");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: BlogGroupResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string url = 3; */
        if (message.url !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.url);
        /* string description = 4; */
        if (message.description !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.description);
        /* string content = 5; */
        if (message.content !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.content);
        /* string status = 6; */
        if (message.status !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.status);
        /* google.protobuf.Timestamp created_at = 7; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 8; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* string org_id = 9; */
        if (message.orgId !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.orgId);
        /* repeated blog.BlogResponse blogs = 10; */
        for (let i = 0; i < message.blogs.length; i++)
            BlogResponse.internalBinaryWrite(message.blogs[i], writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* string created_by = 11; */
        if (message.createdBy !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.createdBy);
        /* string updated_by = 12; */
        if (message.updatedBy !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.updatedBy);
        /* map<string, string> extend_object = 13; */
        for (let k of globalThis.Object.keys(message.extendObject))
            writer.tag(13, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.extendObject[k]).join();
        /* repeated string blog_ids = 14; */
        for (let i = 0; i < message.blogIds.length; i++)
            writer.tag(14, WireType.LengthDelimited).string(message.blogIds[i]);
        /* string group_by = 15; */
        if (message.groupBy !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.groupBy);
        /* string operator = 16; */
        if (message.operator !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.operator);
        /* repeated common.CommonCriteria criteria = 17; */
        for (let i = 0; i < message.criteria.length; i++)
            CommonCriteria.internalBinaryWrite(message.criteria[i], writer.tag(17, WireType.LengthDelimited).fork(), options).join();
        /* string package_index = 18; */
        if (message.packageIndex !== "")
            writer.tag(18, WireType.LengthDelimited).string(message.packageIndex);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message blog.BlogGroupResponse
 */
export const BlogGroupResponse = new BlogGroupResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BlogDataSourceResponse$Type extends MessageType<BlogDataSourceResponse> {
    constructor() {
        super("blog.BlogDataSourceResponse", [
            { no: 1, name: "meta", kind: "message", T: () => CommonDataSourceMeta },
            { no: 2, name: "data", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => BlogResponse }
        ]);
    }
    create(value?: PartialMessage<BlogDataSourceResponse>): BlogDataSourceResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = [];
        if (value !== undefined)
            reflectionMergePartial<BlogDataSourceResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlogDataSourceResponse): BlogDataSourceResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.CommonDataSourceMeta meta */ 1:
                    message.meta = CommonDataSourceMeta.internalBinaryRead(reader, reader.uint32(), options, message.meta);
                    break;
                case /* repeated blog.BlogResponse data */ 2:
                    message.data.push(BlogResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BlogDataSourceResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.CommonDataSourceMeta meta = 1; */
        if (message.meta)
            CommonDataSourceMeta.internalBinaryWrite(message.meta, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated blog.BlogResponse data = 2; */
        for (let i = 0; i < message.data.length; i++)
            BlogResponse.internalBinaryWrite(message.data[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message blog.BlogDataSourceResponse
 */
export const BlogDataSourceResponse = new BlogDataSourceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BlogGroupDataSourceResponse$Type extends MessageType<BlogGroupDataSourceResponse> {
    constructor() {
        super("blog.BlogGroupDataSourceResponse", [
            { no: 1, name: "meta", kind: "message", T: () => CommonDataSourceMeta },
            { no: 2, name: "data", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => BlogGroupResponse }
        ]);
    }
    create(value?: PartialMessage<BlogGroupDataSourceResponse>): BlogGroupDataSourceResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = [];
        if (value !== undefined)
            reflectionMergePartial<BlogGroupDataSourceResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlogGroupDataSourceResponse): BlogGroupDataSourceResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.CommonDataSourceMeta meta */ 1:
                    message.meta = CommonDataSourceMeta.internalBinaryRead(reader, reader.uint32(), options, message.meta);
                    break;
                case /* repeated blog.BlogGroupResponse data */ 2:
                    message.data.push(BlogGroupResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BlogGroupDataSourceResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.CommonDataSourceMeta meta = 1; */
        if (message.meta)
            CommonDataSourceMeta.internalBinaryWrite(message.meta, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated blog.BlogGroupResponse data = 2; */
        for (let i = 0; i < message.data.length; i++)
            BlogGroupResponse.internalBinaryWrite(message.data[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message blog.BlogGroupDataSourceResponse
 */
export const BlogGroupDataSourceResponse = new BlogGroupDataSourceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BlogResponseWrapped$Type extends MessageType<BlogResponseWrapped> {
    constructor() {
        super("blog.BlogResponseWrapped", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "message", T: () => BlogResponse }
        ]);
    }
    create(value?: PartialMessage<BlogResponseWrapped>): BlogResponseWrapped {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<BlogResponseWrapped>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlogResponseWrapped): BlogResponseWrapped {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* blog.BlogResponse data */ 3:
                    message.data = BlogResponse.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BlogResponseWrapped, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* blog.BlogResponse data = 3; */
        if (message.data)
            BlogResponse.internalBinaryWrite(message.data, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message blog.BlogResponseWrapped
 */
export const BlogResponseWrapped = new BlogResponseWrapped$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BlogGroupResponseWrapped$Type extends MessageType<BlogGroupResponseWrapped> {
    constructor() {
        super("blog.BlogGroupResponseWrapped", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "message", T: () => BlogGroupResponse }
        ]);
    }
    create(value?: PartialMessage<BlogGroupResponseWrapped>): BlogGroupResponseWrapped {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<BlogGroupResponseWrapped>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlogGroupResponseWrapped): BlogGroupResponseWrapped {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* blog.BlogGroupResponse data */ 3:
                    message.data = BlogGroupResponse.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BlogGroupResponseWrapped, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* blog.BlogGroupResponse data = 3; */
        if (message.data)
            BlogGroupResponse.internalBinaryWrite(message.data, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message blog.BlogGroupResponseWrapped
 */
export const BlogGroupResponseWrapped = new BlogGroupResponseWrapped$Type();
/**
 * @generated ServiceType for protobuf service blog.BlogService
 */
export const BlogService = new ServiceType("blog.BlogService", [
    { name: "GetBlogsByQuery", options: {}, I: CommonQuery, O: BlogDataSourceResponse },
    { name: "GetBlogDetail", options: {}, I: GetBySlugRequest, O: BlogResponseWrapped },
    { name: "GetBlogsByBlogGroupSlug", options: {}, I: GetBySlugPagedRequest, O: BlogDataSourceResponse },
    { name: "GetBlogGroupsByQuery", options: {}, I: CommonQuery, O: BlogGroupDataSourceResponse },
    { name: "GetBlogGroupsBySlug", options: {}, I: GetBySlugRequest, O: BlogGroupResponseWrapped }
]);
