// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/comment.proto" (package "comment", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message comment.CreateCommentRequest
 */
export interface CreateCommentRequest {
    /**
     * @generated from protobuf field: string ref_id = 1
     */
    refId: string;
    /**
     * @generated from protobuf field: string ref_type = 2
     */
    refType: string; // blog, product, ...
    /**
     * @generated from protobuf field: string content = 3
     */
    content: string;
}
/**
 * @generated from protobuf message comment.CreateCommentResponse
 */
export interface CreateCommentResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: comment.CommentData data = 3
     */
    data?: CommentData;
}
/**
 * @generated from protobuf message comment.GetCommentsByRefRequest
 */
export interface GetCommentsByRefRequest {
    /**
     * @generated from protobuf field: string ref_id = 1
     */
    refId: string;
    /**
     * @generated from protobuf field: string ref_type = 2
     */
    refType: string;
    /**
     * @generated from protobuf field: int32 page_number = 3
     */
    pageNumber: number;
    /**
     * @generated from protobuf field: int32 page_size = 4
     */
    pageSize: number;
}
/**
 * @generated from protobuf message comment.GetCommentsByRefResponse
 */
export interface GetCommentsByRefResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: repeated comment.CommentData data = 3
     */
    data: CommentData[];
}
/**
 * @generated from protobuf message comment.CommentData
 */
export interface CommentData {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string ref_id = 2
     */
    refId: string;
    /**
     * @generated from protobuf field: string ref_type = 3
     */
    refType: string;
    /**
     * @generated from protobuf field: string user_id = 4
     */
    userId: string;
    /**
     * @generated from protobuf field: string user_display_name = 5
     */
    userDisplayName: string;
    /**
     * @generated from protobuf field: string user_avatar_url = 6
     */
    userAvatarUrl: string;
    /**
     * @generated from protobuf field: string content = 7
     */
    content: string;
    /**
     * @generated from protobuf field: string status = 8
     */
    status: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 9
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: string rejection_reason = 10
     */
    rejectionReason: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 11
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: string org_id = 12
     */
    orgId: string;
    /**
     * @generated from protobuf field: string created_by = 13
     */
    createdBy: string;
    /**
     * @generated from protobuf field: string updated_by = 14
     */
    updatedBy: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateCommentRequest$Type extends MessageType<CreateCommentRequest> {
    constructor() {
        super("comment.CreateCommentRequest", [
            { no: 1, name: "ref_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "ref_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateCommentRequest>): CreateCommentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.refId = "";
        message.refType = "";
        message.content = "";
        if (value !== undefined)
            reflectionMergePartial<CreateCommentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateCommentRequest): CreateCommentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string ref_id */ 1:
                    message.refId = reader.string();
                    break;
                case /* string ref_type */ 2:
                    message.refType = reader.string();
                    break;
                case /* string content */ 3:
                    message.content = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateCommentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string ref_id = 1; */
        if (message.refId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.refId);
        /* string ref_type = 2; */
        if (message.refType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.refType);
        /* string content = 3; */
        if (message.content !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.content);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message comment.CreateCommentRequest
 */
export const CreateCommentRequest = new CreateCommentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateCommentResponse$Type extends MessageType<CreateCommentResponse> {
    constructor() {
        super("comment.CreateCommentResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "message", T: () => CommentData }
        ]);
    }
    create(value?: PartialMessage<CreateCommentResponse>): CreateCommentResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<CreateCommentResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateCommentResponse): CreateCommentResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* comment.CommentData data */ 3:
                    message.data = CommentData.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateCommentResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* comment.CommentData data = 3; */
        if (message.data)
            CommentData.internalBinaryWrite(message.data, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message comment.CreateCommentResponse
 */
export const CreateCommentResponse = new CreateCommentResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCommentsByRefRequest$Type extends MessageType<GetCommentsByRefRequest> {
    constructor() {
        super("comment.GetCommentsByRefRequest", [
            { no: 1, name: "ref_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "ref_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "page_number", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "page_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetCommentsByRefRequest>): GetCommentsByRefRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.refId = "";
        message.refType = "";
        message.pageNumber = 0;
        message.pageSize = 0;
        if (value !== undefined)
            reflectionMergePartial<GetCommentsByRefRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCommentsByRefRequest): GetCommentsByRefRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string ref_id */ 1:
                    message.refId = reader.string();
                    break;
                case /* string ref_type */ 2:
                    message.refType = reader.string();
                    break;
                case /* int32 page_number */ 3:
                    message.pageNumber = reader.int32();
                    break;
                case /* int32 page_size */ 4:
                    message.pageSize = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCommentsByRefRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string ref_id = 1; */
        if (message.refId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.refId);
        /* string ref_type = 2; */
        if (message.refType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.refType);
        /* int32 page_number = 3; */
        if (message.pageNumber !== 0)
            writer.tag(3, WireType.Varint).int32(message.pageNumber);
        /* int32 page_size = 4; */
        if (message.pageSize !== 0)
            writer.tag(4, WireType.Varint).int32(message.pageSize);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message comment.GetCommentsByRefRequest
 */
export const GetCommentsByRefRequest = new GetCommentsByRefRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCommentsByRefResponse$Type extends MessageType<GetCommentsByRefResponse> {
    constructor() {
        super("comment.GetCommentsByRefResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CommentData }
        ]);
    }
    create(value?: PartialMessage<GetCommentsByRefResponse>): GetCommentsByRefResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        message.data = [];
        if (value !== undefined)
            reflectionMergePartial<GetCommentsByRefResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCommentsByRefResponse): GetCommentsByRefResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* repeated comment.CommentData data */ 3:
                    message.data.push(CommentData.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCommentsByRefResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* repeated comment.CommentData data = 3; */
        for (let i = 0; i < message.data.length; i++)
            CommentData.internalBinaryWrite(message.data[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message comment.GetCommentsByRefResponse
 */
export const GetCommentsByRefResponse = new GetCommentsByRefResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CommentData$Type extends MessageType<CommentData> {
    constructor() {
        super("comment.CommentData", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "ref_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "ref_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "user_display_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "user_avatar_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 10, name: "rejection_reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 12, name: "org_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "created_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "updated_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CommentData>): CommentData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.refId = "";
        message.refType = "";
        message.userId = "";
        message.userDisplayName = "";
        message.userAvatarUrl = "";
        message.content = "";
        message.status = "";
        message.rejectionReason = "";
        message.orgId = "";
        message.createdBy = "";
        message.updatedBy = "";
        if (value !== undefined)
            reflectionMergePartial<CommentData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CommentData): CommentData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string ref_id */ 2:
                    message.refId = reader.string();
                    break;
                case /* string ref_type */ 3:
                    message.refType = reader.string();
                    break;
                case /* string user_id */ 4:
                    message.userId = reader.string();
                    break;
                case /* string user_display_name */ 5:
                    message.userDisplayName = reader.string();
                    break;
                case /* string user_avatar_url */ 6:
                    message.userAvatarUrl = reader.string();
                    break;
                case /* string content */ 7:
                    message.content = reader.string();
                    break;
                case /* string status */ 8:
                    message.status = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 9:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* string rejection_reason */ 10:
                    message.rejectionReason = reader.string();
                    break;
                case /* google.protobuf.Timestamp updated_at */ 11:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* string org_id */ 12:
                    message.orgId = reader.string();
                    break;
                case /* string created_by */ 13:
                    message.createdBy = reader.string();
                    break;
                case /* string updated_by */ 14:
                    message.updatedBy = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CommentData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string ref_id = 2; */
        if (message.refId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.refId);
        /* string ref_type = 3; */
        if (message.refType !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.refType);
        /* string user_id = 4; */
        if (message.userId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.userId);
        /* string user_display_name = 5; */
        if (message.userDisplayName !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.userDisplayName);
        /* string user_avatar_url = 6; */
        if (message.userAvatarUrl !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.userAvatarUrl);
        /* string content = 7; */
        if (message.content !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.content);
        /* string status = 8; */
        if (message.status !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.status);
        /* google.protobuf.Timestamp created_at = 9; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* string rejection_reason = 10; */
        if (message.rejectionReason !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.rejectionReason);
        /* google.protobuf.Timestamp updated_at = 11; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* string org_id = 12; */
        if (message.orgId !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.orgId);
        /* string created_by = 13; */
        if (message.createdBy !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.createdBy);
        /* string updated_by = 14; */
        if (message.updatedBy !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.updatedBy);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message comment.CommentData
 */
export const CommentData = new CommentData$Type();
/**
 * @generated ServiceType for protobuf service comment.CommentService
 */
export const CommentService = new ServiceType("comment.CommentService", [
    { name: "CreateComment", options: {}, I: CreateCommentRequest, O: CreateCommentResponse },
    { name: "GetCommentsByRef", options: {}, I: GetCommentsByRefRequest, O: GetCommentsByRefResponse }
]);
