// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/comment.proto" (package "comment", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CommentService } from "./comment";
import type { GetCommentsByRefResponse } from "./comment";
import type { GetCommentsByRefRequest } from "./comment";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateCommentResponse } from "./comment";
import type { CreateCommentRequest } from "./comment";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service comment.CommentService
 */
export interface ICommentServiceClient {
    /**
     * @generated from protobuf rpc: CreateComment
     */
    createComment(input: CreateCommentRequest, options?: RpcOptions): UnaryCall<CreateCommentRequest, CreateCommentResponse>;
    /**
     * @generated from protobuf rpc: GetCommentsByRef
     */
    getCommentsByRef(input: GetCommentsByRefRequest, options?: RpcOptions): UnaryCall<GetCommentsByRefRequest, GetCommentsByRefResponse>;
}
/**
 * @generated from protobuf service comment.CommentService
 */
export class CommentServiceClient implements ICommentServiceClient, ServiceInfo {
    typeName = CommentService.typeName;
    methods = CommentService.methods;
    options = CommentService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateComment
     */
    createComment(input: CreateCommentRequest, options?: RpcOptions): UnaryCall<CreateCommentRequest, CreateCommentResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateCommentRequest, CreateCommentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCommentsByRef
     */
    getCommentsByRef(input: GetCommentsByRefRequest, options?: RpcOptions): UnaryCall<GetCommentsByRefRequest, GetCommentsByRefResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCommentsByRefRequest, GetCommentsByRefResponse>("unary", this._transport, method, opt, input);
    }
}
