// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/order.proto" (package "order", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { OrderService } from "./order";
import type { SubmitReviewRequest } from "./order";
import type { RequestRefundRequest } from "./order";
import type { GetOrderTrackingResponse } from "./order";
import type { CancelOrderRequest } from "./order";
import type { OrderDetailResponse } from "./order";
import type { GetOrderRequest } from "./order";
import type { GetOrdersResponse } from "./order";
import type { CommonQuery } from "./common";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { OperationResult } from "./common";
import type { PlaceOrderRequest } from "./order";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service order.OrderService
 */
export interface IOrderServiceClient {
    /**
     * @generated from protobuf rpc: PlaceOrder
     */
    placeOrder(input: PlaceOrderRequest, options?: RpcOptions): UnaryCall<PlaceOrderRequest, OperationResult>;
    /**
     * @generated from protobuf rpc: GetMyOrders
     */
    getMyOrders(input: CommonQuery, options?: RpcOptions): UnaryCall<CommonQuery, GetOrdersResponse>;
    /**
     * @generated from protobuf rpc: GetOrderDetail
     */
    getOrderDetail(input: GetOrderRequest, options?: RpcOptions): UnaryCall<GetOrderRequest, OrderDetailResponse>;
    /**
     * @generated from protobuf rpc: CancelOrder
     */
    cancelOrder(input: CancelOrderRequest, options?: RpcOptions): UnaryCall<CancelOrderRequest, OperationResult>;
    /**
     * @generated from protobuf rpc: GetOrderTracking
     */
    getOrderTracking(input: GetOrderRequest, options?: RpcOptions): UnaryCall<GetOrderRequest, GetOrderTrackingResponse>;
    /**
     * @generated from protobuf rpc: RequestRefund
     */
    requestRefund(input: RequestRefundRequest, options?: RpcOptions): UnaryCall<RequestRefundRequest, OperationResult>;
    /**
     * @generated from protobuf rpc: SubmitReview
     */
    submitReview(input: SubmitReviewRequest, options?: RpcOptions): UnaryCall<SubmitReviewRequest, OperationResult>;
}
/**
 * @generated from protobuf service order.OrderService
 */
export class OrderServiceClient implements IOrderServiceClient, ServiceInfo {
    typeName = OrderService.typeName;
    methods = OrderService.methods;
    options = OrderService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: PlaceOrder
     */
    placeOrder(input: PlaceOrderRequest, options?: RpcOptions): UnaryCall<PlaceOrderRequest, OperationResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<PlaceOrderRequest, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMyOrders
     */
    getMyOrders(input: CommonQuery, options?: RpcOptions): UnaryCall<CommonQuery, GetOrdersResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CommonQuery, GetOrdersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetOrderDetail
     */
    getOrderDetail(input: GetOrderRequest, options?: RpcOptions): UnaryCall<GetOrderRequest, OrderDetailResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOrderRequest, OrderDetailResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CancelOrder
     */
    cancelOrder(input: CancelOrderRequest, options?: RpcOptions): UnaryCall<CancelOrderRequest, OperationResult> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<CancelOrderRequest, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetOrderTracking
     */
    getOrderTracking(input: GetOrderRequest, options?: RpcOptions): UnaryCall<GetOrderRequest, GetOrderTrackingResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOrderRequest, GetOrderTrackingResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RequestRefund
     */
    requestRefund(input: RequestRefundRequest, options?: RpcOptions): UnaryCall<RequestRefundRequest, OperationResult> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<RequestRefundRequest, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SubmitReview
     */
    submitReview(input: SubmitReviewRequest, options?: RpcOptions): UnaryCall<SubmitReviewRequest, OperationResult> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<SubmitReviewRequest, OperationResult>("unary", this._transport, method, opt, input);
    }
}
