// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/order.proto" (package "order", syntax proto3)
// tslint:disable
import { CommonQuery } from "./common";
import { OperationResult } from "./common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message order.PlaceOrderRequest
 */
export interface PlaceOrderRequest {
    /**
     * @generated from protobuf field: string customer_name = 1
     */
    customerName: string;
    /**
     * @generated from protobuf field: string email = 2
     */
    email: string;
    /**
     * @generated from protobuf field: string phone = 3
     */
    phone: string;
    /**
     * @generated from protobuf field: string shipping_address = 4
     */
    shippingAddress: string;
    /**
     * @generated from protobuf field: string payment_method = 5
     */
    paymentMethod: string;
    /**
     * @generated from protobuf field: string note = 6
     */
    note: string;
    /**
     * @generated from protobuf field: string session_id = 7
     */
    sessionId: string;
    /**
     * @generated from protobuf field: repeated order.OrderItemInput items = 10
     */
    items: OrderItemInput[];
    /**
     * @generated from protobuf field: string voucher_code = 11
     */
    voucherCode: string;
    /**
     * @generated from protobuf field: double shipping_fee = 12
     */
    shippingFee: number;
    /**
     * @generated from protobuf field: string shipping_carrier_pref = 13
     */
    shippingCarrierPref: string;
}
/**
 * @generated from protobuf message order.OrderItemInput
 */
export interface OrderItemInput {
    /**
     * @generated from protobuf field: string product_id = 1
     */
    productId: string;
    /**
     * @generated from protobuf field: string variant_id = 2
     */
    variantId: string;
    /**
     * @generated from protobuf field: int32 qty = 3
     */
    qty: number;
}
/**
 * @generated from protobuf message order.GetOrdersResponse
 */
export interface GetOrdersResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: int32 total = 3
     */
    total: number;
    /**
     * @generated from protobuf field: repeated order.OrderResponse data = 4
     */
    data: OrderResponse[];
}
/**
 * @generated from protobuf message order.OrderResponse
 */
export interface OrderResponse {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string order_code = 2
     */
    orderCode: string;
    /**
     * @generated from protobuf field: string customer_name = 3
     */
    customerName: string;
    /**
     * @generated from protobuf field: string email = 4
     */
    email: string;
    /**
     * @generated from protobuf field: string phone = 5
     */
    phone: string;
    /**
     * @generated from protobuf field: string status = 6
     */
    status: string;
    /**
     * @generated from protobuf field: string payment_status = 7
     */
    paymentStatus: string;
    /**
     * @generated from protobuf field: double total_amount = 8
     */
    totalAmount: number;
    /**
     * @generated from protobuf field: int64 created_at = 9
     */
    createdAt: bigint;
    /**
     * @generated from protobuf field: string shipping_address = 10
     */
    shippingAddress: string;
    /**
     * @generated from protobuf field: string shipping_carrier = 11
     */
    shippingCarrier: string;
    /**
     * @generated from protobuf field: string tracking_code = 12
     */
    trackingCode: string;
    /**
     * @generated from protobuf field: int64 estimated_delivery_from = 13
     */
    estimatedDeliveryFrom: bigint;
    /**
     * @generated from protobuf field: int64 estimated_delivery_to = 14
     */
    estimatedDeliveryTo: bigint;
    /**
     * @generated from protobuf field: int64 shipped_at = 15
     */
    shippedAt: bigint;
    /**
     * @generated from protobuf field: int64 delivered_at = 16
     */
    deliveredAt: bigint;
    /**
     * TIKTOK STYLE FIELDS
     *
     * @generated from protobuf field: string shop_name = 17
     */
    shopName: string;
    /**
     * @generated from protobuf field: string payment_method_label = 18
     */
    paymentMethodLabel: string;
    /**
     * @generated from protobuf field: string payment_method_logo = 19
     */
    paymentMethodLogo: string;
    /**
     * @generated from protobuf field: double shipping_fee = 20
     */
    shippingFee: number;
    /**
     * @generated from protobuf field: double discount_amount = 21
     */
    discountAmount: number;
    /**
     * @generated from protobuf field: double original_total_amount = 22
     */
    originalTotalAmount: number;
    /**
     * @generated from protobuf field: int64 paid_at = 23
     */
    paidAt: bigint;
    /**
     * @generated from protobuf field: string shop_logo_url = 24
     */
    shopLogoUrl: string;
    /**
     * @generated from protobuf field: string status_label = 25
     */
    statusLabel: string;
    /**
     * @generated from protobuf field: string status_emoji = 26
     */
    statusEmoji: string;
    /**
     * @generated from protobuf field: string shop_id = 27
     */
    shopId: string;
    /**
     * @generated from protobuf field: int64 expected_delivery_date = 28
     */
    expectedDeliveryDate: bigint;
    /**
     * @generated from protobuf field: string payment_method = 29
     */
    paymentMethod: string;
    /**
     * @generated from protobuf field: string note = 30
     */
    note: string;
    /**
     * @generated from protobuf field: string voucher_code = 31
     */
    voucherCode: string;
    /**
     * @generated from protobuf field: string cancel_reason = 32
     */
    cancelReason: string;
    /**
     * @generated from protobuf field: string cancelled_by = 33
     */
    cancelledBy: string;
    /**
     * @generated from protobuf field: int64 cancelled_at = 34
     */
    cancelledAt: bigint;
    /**
     * @generated from protobuf field: string tracking_url = 35
     */
    trackingUrl: string;
    /**
     * @generated from protobuf field: double tax_amount = 36
     */
    taxAmount: number;
}
/**
 * @generated from protobuf message order.CancelOrderRequest
 */
export interface CancelOrderRequest {
    /**
     * @generated from protobuf field: string order_code = 1
     */
    orderCode: string;
    /**
     * @generated from protobuf field: string reason = 2
     */
    reason: string;
    /**
     * @generated from protobuf field: string session_id = 3
     */
    sessionId: string;
}
/**
 * @generated from protobuf message order.GetOrderRequest
 */
export interface GetOrderRequest {
    /**
     * @generated from protobuf field: string slug = 1
     */
    slug: string;
    /**
     * @generated from protobuf field: string session_id = 2
     */
    sessionId: string;
}
/**
 * @generated from protobuf message order.GetOrderTrackingResponse
 */
export interface GetOrderTrackingResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string tracking_code = 2
     */
    trackingCode: string;
    /**
     * @generated from protobuf field: string carrier = 3
     */
    carrier: string;
    /**
     * @generated from protobuf field: string carrier_url = 4
     */
    carrierUrl: string;
    /**
     * @generated from protobuf field: int64 estimated_from = 5
     */
    estimatedFrom: bigint;
    /**
     * @generated from protobuf field: int64 estimated_to = 6
     */
    estimatedTo: bigint;
    /**
     * @generated from protobuf field: repeated order.TrackingEvent events = 7
     */
    events: TrackingEvent[];
    /**
     * @generated from protobuf field: string message = 8
     */
    message: string;
}
/**
 * @generated from protobuf message order.TrackingEvent
 */
export interface TrackingEvent {
    /**
     * @generated from protobuf field: int64 event_time = 1
     */
    eventTime: bigint;
    /**
     * @generated from protobuf field: string location = 2
     */
    location: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string;
    /**
     * @generated from protobuf field: string status = 4
     */
    status: string;
    /**
     * @generated from protobuf field: bool is_current = 5
     */
    isCurrent: boolean;
}
/**
 * @generated from protobuf message order.OrderDetailResponse
 */
export interface OrderDetailResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: order.OrderResponse order = 3
     */
    order?: OrderResponse;
    /**
     * @generated from protobuf field: repeated order.OrderItemResponse items = 4
     */
    items: OrderItemResponse[];
}
/**
 * @generated from protobuf message order.OrderItemResponse
 */
export interface OrderItemResponse {
    /**
     * @generated from protobuf field: string product_name = 1
     */
    productName: string;
    /**
     * @generated from protobuf field: string variant_name = 2
     */
    variantName: string;
    /**
     * @generated from protobuf field: double price = 3
     */
    price: number;
    /**
     * @generated from protobuf field: int32 qty = 4
     */
    qty: number;
    /**
     * @generated from protobuf field: string image_url = 5
     */
    imageUrl: string;
    /**
     * @generated from protobuf field: double sub_total = 6
     */
    subTotal: number;
}
/**
 * @generated from protobuf message order.RequestRefundRequest
 */
export interface RequestRefundRequest {
    /**
     * @generated from protobuf field: string order_code = 1
     */
    orderCode: string;
    /**
     * @generated from protobuf field: string reason = 2
     */
    reason: string;
    /**
     * @generated from protobuf field: string refund_type = 3
     */
    refundType: string; // "Refund" | "ReturnRefund"
    /**
     * @generated from protobuf field: double amount = 4
     */
    amount: number;
    /**
     * @generated from protobuf field: repeated string evidence_urls = 5
     */
    evidenceUrls: string[];
    /**
     * @generated from protobuf field: string session_id = 6
     */
    sessionId: string;
}
/**
 * @generated from protobuf message order.SubmitReviewRequest
 */
export interface SubmitReviewRequest {
    /**
     * @generated from protobuf field: string order_id = 1
     */
    orderId: string;
    /**
     * @generated from protobuf field: string order_item_id = 2
     */
    orderItemId: string;
    /**
     * @generated from protobuf field: int32 rating = 3
     */
    rating: number;
    /**
     * @generated from protobuf field: string comment = 4
     */
    comment: string;
    /**
     * @generated from protobuf field: repeated string media_urls = 5
     */
    mediaUrls: string[];
    /**
     * @generated from protobuf field: bool is_anonymous = 6
     */
    isAnonymous: boolean;
    /**
     * @generated from protobuf field: string session_id = 7
     */
    sessionId: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class PlaceOrderRequest$Type extends MessageType<PlaceOrderRequest> {
    constructor() {
        super("order.PlaceOrderRequest", [
            { no: 1, name: "customer_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "shipping_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "payment_method", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "note", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => OrderItemInput },
            { no: 11, name: "voucher_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "shipping_fee", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 13, name: "shipping_carrier_pref", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PlaceOrderRequest>): PlaceOrderRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.customerName = "";
        message.email = "";
        message.phone = "";
        message.shippingAddress = "";
        message.paymentMethod = "";
        message.note = "";
        message.sessionId = "";
        message.items = [];
        message.voucherCode = "";
        message.shippingFee = 0;
        message.shippingCarrierPref = "";
        if (value !== undefined)
            reflectionMergePartial<PlaceOrderRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlaceOrderRequest): PlaceOrderRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string customer_name */ 1:
                    message.customerName = reader.string();
                    break;
                case /* string email */ 2:
                    message.email = reader.string();
                    break;
                case /* string phone */ 3:
                    message.phone = reader.string();
                    break;
                case /* string shipping_address */ 4:
                    message.shippingAddress = reader.string();
                    break;
                case /* string payment_method */ 5:
                    message.paymentMethod = reader.string();
                    break;
                case /* string note */ 6:
                    message.note = reader.string();
                    break;
                case /* string session_id */ 7:
                    message.sessionId = reader.string();
                    break;
                case /* repeated order.OrderItemInput items */ 10:
                    message.items.push(OrderItemInput.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string voucher_code */ 11:
                    message.voucherCode = reader.string();
                    break;
                case /* double shipping_fee */ 12:
                    message.shippingFee = reader.double();
                    break;
                case /* string shipping_carrier_pref */ 13:
                    message.shippingCarrierPref = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PlaceOrderRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string customer_name = 1; */
        if (message.customerName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.customerName);
        /* string email = 2; */
        if (message.email !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.email);
        /* string phone = 3; */
        if (message.phone !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.phone);
        /* string shipping_address = 4; */
        if (message.shippingAddress !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.shippingAddress);
        /* string payment_method = 5; */
        if (message.paymentMethod !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.paymentMethod);
        /* string note = 6; */
        if (message.note !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.note);
        /* string session_id = 7; */
        if (message.sessionId !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.sessionId);
        /* repeated order.OrderItemInput items = 10; */
        for (let i = 0; i < message.items.length; i++)
            OrderItemInput.internalBinaryWrite(message.items[i], writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* string voucher_code = 11; */
        if (message.voucherCode !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.voucherCode);
        /* double shipping_fee = 12; */
        if (message.shippingFee !== 0)
            writer.tag(12, WireType.Bit64).double(message.shippingFee);
        /* string shipping_carrier_pref = 13; */
        if (message.shippingCarrierPref !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.shippingCarrierPref);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message order.PlaceOrderRequest
 */
export const PlaceOrderRequest = new PlaceOrderRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OrderItemInput$Type extends MessageType<OrderItemInput> {
    constructor() {
        super("order.OrderItemInput", [
            { no: 1, name: "product_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "variant_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "qty", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<OrderItemInput>): OrderItemInput {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.productId = "";
        message.variantId = "";
        message.qty = 0;
        if (value !== undefined)
            reflectionMergePartial<OrderItemInput>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OrderItemInput): OrderItemInput {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string product_id */ 1:
                    message.productId = reader.string();
                    break;
                case /* string variant_id */ 2:
                    message.variantId = reader.string();
                    break;
                case /* int32 qty */ 3:
                    message.qty = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OrderItemInput, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string product_id = 1; */
        if (message.productId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.productId);
        /* string variant_id = 2; */
        if (message.variantId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.variantId);
        /* int32 qty = 3; */
        if (message.qty !== 0)
            writer.tag(3, WireType.Varint).int32(message.qty);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message order.OrderItemInput
 */
export const OrderItemInput = new OrderItemInput$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOrdersResponse$Type extends MessageType<GetOrdersResponse> {
    constructor() {
        super("order.GetOrdersResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "total", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "data", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => OrderResponse }
        ]);
    }
    create(value?: PartialMessage<GetOrdersResponse>): GetOrdersResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        message.total = 0;
        message.data = [];
        if (value !== undefined)
            reflectionMergePartial<GetOrdersResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetOrdersResponse): GetOrdersResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* int32 total */ 3:
                    message.total = reader.int32();
                    break;
                case /* repeated order.OrderResponse data */ 4:
                    message.data.push(OrderResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetOrdersResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* int32 total = 3; */
        if (message.total !== 0)
            writer.tag(3, WireType.Varint).int32(message.total);
        /* repeated order.OrderResponse data = 4; */
        for (let i = 0; i < message.data.length; i++)
            OrderResponse.internalBinaryWrite(message.data[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message order.GetOrdersResponse
 */
export const GetOrdersResponse = new GetOrdersResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OrderResponse$Type extends MessageType<OrderResponse> {
    constructor() {
        super("order.OrderResponse", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "order_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "customer_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "payment_status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "total_amount", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 9, name: "created_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 10, name: "shipping_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "shipping_carrier", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "tracking_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "estimated_delivery_from", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 14, name: "estimated_delivery_to", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 15, name: "shipped_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 16, name: "delivered_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 17, name: "shop_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "payment_method_label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "payment_method_logo", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 20, name: "shipping_fee", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 21, name: "discount_amount", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 22, name: "original_total_amount", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 23, name: "paid_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 24, name: "shop_logo_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 25, name: "status_label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 26, name: "status_emoji", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 27, name: "shop_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 28, name: "expected_delivery_date", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 29, name: "payment_method", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 30, name: "note", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 31, name: "voucher_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 32, name: "cancel_reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 33, name: "cancelled_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 34, name: "cancelled_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 35, name: "tracking_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 36, name: "tax_amount", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<OrderResponse>): OrderResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.orderCode = "";
        message.customerName = "";
        message.email = "";
        message.phone = "";
        message.status = "";
        message.paymentStatus = "";
        message.totalAmount = 0;
        message.createdAt = 0n;
        message.shippingAddress = "";
        message.shippingCarrier = "";
        message.trackingCode = "";
        message.estimatedDeliveryFrom = 0n;
        message.estimatedDeliveryTo = 0n;
        message.shippedAt = 0n;
        message.deliveredAt = 0n;
        message.shopName = "";
        message.paymentMethodLabel = "";
        message.paymentMethodLogo = "";
        message.shippingFee = 0;
        message.discountAmount = 0;
        message.originalTotalAmount = 0;
        message.paidAt = 0n;
        message.shopLogoUrl = "";
        message.statusLabel = "";
        message.statusEmoji = "";
        message.shopId = "";
        message.expectedDeliveryDate = 0n;
        message.paymentMethod = "";
        message.note = "";
        message.voucherCode = "";
        message.cancelReason = "";
        message.cancelledBy = "";
        message.cancelledAt = 0n;
        message.trackingUrl = "";
        message.taxAmount = 0;
        if (value !== undefined)
            reflectionMergePartial<OrderResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OrderResponse): OrderResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string order_code */ 2:
                    message.orderCode = reader.string();
                    break;
                case /* string customer_name */ 3:
                    message.customerName = reader.string();
                    break;
                case /* string email */ 4:
                    message.email = reader.string();
                    break;
                case /* string phone */ 5:
                    message.phone = reader.string();
                    break;
                case /* string status */ 6:
                    message.status = reader.string();
                    break;
                case /* string payment_status */ 7:
                    message.paymentStatus = reader.string();
                    break;
                case /* double total_amount */ 8:
                    message.totalAmount = reader.double();
                    break;
                case /* int64 created_at */ 9:
                    message.createdAt = reader.int64().toBigInt();
                    break;
                case /* string shipping_address */ 10:
                    message.shippingAddress = reader.string();
                    break;
                case /* string shipping_carrier */ 11:
                    message.shippingCarrier = reader.string();
                    break;
                case /* string tracking_code */ 12:
                    message.trackingCode = reader.string();
                    break;
                case /* int64 estimated_delivery_from */ 13:
                    message.estimatedDeliveryFrom = reader.int64().toBigInt();
                    break;
                case /* int64 estimated_delivery_to */ 14:
                    message.estimatedDeliveryTo = reader.int64().toBigInt();
                    break;
                case /* int64 shipped_at */ 15:
                    message.shippedAt = reader.int64().toBigInt();
                    break;
                case /* int64 delivered_at */ 16:
                    message.deliveredAt = reader.int64().toBigInt();
                    break;
                case /* string shop_name */ 17:
                    message.shopName = reader.string();
                    break;
                case /* string payment_method_label */ 18:
                    message.paymentMethodLabel = reader.string();
                    break;
                case /* string payment_method_logo */ 19:
                    message.paymentMethodLogo = reader.string();
                    break;
                case /* double shipping_fee */ 20:
                    message.shippingFee = reader.double();
                    break;
                case /* double discount_amount */ 21:
                    message.discountAmount = reader.double();
                    break;
                case /* double original_total_amount */ 22:
                    message.originalTotalAmount = reader.double();
                    break;
                case /* int64 paid_at */ 23:
                    message.paidAt = reader.int64().toBigInt();
                    break;
                case /* string shop_logo_url */ 24:
                    message.shopLogoUrl = reader.string();
                    break;
                case /* string status_label */ 25:
                    message.statusLabel = reader.string();
                    break;
                case /* string status_emoji */ 26:
                    message.statusEmoji = reader.string();
                    break;
                case /* string shop_id */ 27:
                    message.shopId = reader.string();
                    break;
                case /* int64 expected_delivery_date */ 28:
                    message.expectedDeliveryDate = reader.int64().toBigInt();
                    break;
                case /* string payment_method */ 29:
                    message.paymentMethod = reader.string();
                    break;
                case /* string note */ 30:
                    message.note = reader.string();
                    break;
                case /* string voucher_code */ 31:
                    message.voucherCode = reader.string();
                    break;
                case /* string cancel_reason */ 32:
                    message.cancelReason = reader.string();
                    break;
                case /* string cancelled_by */ 33:
                    message.cancelledBy = reader.string();
                    break;
                case /* int64 cancelled_at */ 34:
                    message.cancelledAt = reader.int64().toBigInt();
                    break;
                case /* string tracking_url */ 35:
                    message.trackingUrl = reader.string();
                    break;
                case /* double tax_amount */ 36:
                    message.taxAmount = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OrderResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string order_code = 2; */
        if (message.orderCode !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.orderCode);
        /* string customer_name = 3; */
        if (message.customerName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.customerName);
        /* string email = 4; */
        if (message.email !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.email);
        /* string phone = 5; */
        if (message.phone !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.phone);
        /* string status = 6; */
        if (message.status !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.status);
        /* string payment_status = 7; */
        if (message.paymentStatus !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.paymentStatus);
        /* double total_amount = 8; */
        if (message.totalAmount !== 0)
            writer.tag(8, WireType.Bit64).double(message.totalAmount);
        /* int64 created_at = 9; */
        if (message.createdAt !== 0n)
            writer.tag(9, WireType.Varint).int64(message.createdAt);
        /* string shipping_address = 10; */
        if (message.shippingAddress !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.shippingAddress);
        /* string shipping_carrier = 11; */
        if (message.shippingCarrier !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.shippingCarrier);
        /* string tracking_code = 12; */
        if (message.trackingCode !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.trackingCode);
        /* int64 estimated_delivery_from = 13; */
        if (message.estimatedDeliveryFrom !== 0n)
            writer.tag(13, WireType.Varint).int64(message.estimatedDeliveryFrom);
        /* int64 estimated_delivery_to = 14; */
        if (message.estimatedDeliveryTo !== 0n)
            writer.tag(14, WireType.Varint).int64(message.estimatedDeliveryTo);
        /* int64 shipped_at = 15; */
        if (message.shippedAt !== 0n)
            writer.tag(15, WireType.Varint).int64(message.shippedAt);
        /* int64 delivered_at = 16; */
        if (message.deliveredAt !== 0n)
            writer.tag(16, WireType.Varint).int64(message.deliveredAt);
        /* string shop_name = 17; */
        if (message.shopName !== "")
            writer.tag(17, WireType.LengthDelimited).string(message.shopName);
        /* string payment_method_label = 18; */
        if (message.paymentMethodLabel !== "")
            writer.tag(18, WireType.LengthDelimited).string(message.paymentMethodLabel);
        /* string payment_method_logo = 19; */
        if (message.paymentMethodLogo !== "")
            writer.tag(19, WireType.LengthDelimited).string(message.paymentMethodLogo);
        /* double shipping_fee = 20; */
        if (message.shippingFee !== 0)
            writer.tag(20, WireType.Bit64).double(message.shippingFee);
        /* double discount_amount = 21; */
        if (message.discountAmount !== 0)
            writer.tag(21, WireType.Bit64).double(message.discountAmount);
        /* double original_total_amount = 22; */
        if (message.originalTotalAmount !== 0)
            writer.tag(22, WireType.Bit64).double(message.originalTotalAmount);
        /* int64 paid_at = 23; */
        if (message.paidAt !== 0n)
            writer.tag(23, WireType.Varint).int64(message.paidAt);
        /* string shop_logo_url = 24; */
        if (message.shopLogoUrl !== "")
            writer.tag(24, WireType.LengthDelimited).string(message.shopLogoUrl);
        /* string status_label = 25; */
        if (message.statusLabel !== "")
            writer.tag(25, WireType.LengthDelimited).string(message.statusLabel);
        /* string status_emoji = 26; */
        if (message.statusEmoji !== "")
            writer.tag(26, WireType.LengthDelimited).string(message.statusEmoji);
        /* string shop_id = 27; */
        if (message.shopId !== "")
            writer.tag(27, WireType.LengthDelimited).string(message.shopId);
        /* int64 expected_delivery_date = 28; */
        if (message.expectedDeliveryDate !== 0n)
            writer.tag(28, WireType.Varint).int64(message.expectedDeliveryDate);
        /* string payment_method = 29; */
        if (message.paymentMethod !== "")
            writer.tag(29, WireType.LengthDelimited).string(message.paymentMethod);
        /* string note = 30; */
        if (message.note !== "")
            writer.tag(30, WireType.LengthDelimited).string(message.note);
        /* string voucher_code = 31; */
        if (message.voucherCode !== "")
            writer.tag(31, WireType.LengthDelimited).string(message.voucherCode);
        /* string cancel_reason = 32; */
        if (message.cancelReason !== "")
            writer.tag(32, WireType.LengthDelimited).string(message.cancelReason);
        /* string cancelled_by = 33; */
        if (message.cancelledBy !== "")
            writer.tag(33, WireType.LengthDelimited).string(message.cancelledBy);
        /* int64 cancelled_at = 34; */
        if (message.cancelledAt !== 0n)
            writer.tag(34, WireType.Varint).int64(message.cancelledAt);
        /* string tracking_url = 35; */
        if (message.trackingUrl !== "")
            writer.tag(35, WireType.LengthDelimited).string(message.trackingUrl);
        /* double tax_amount = 36; */
        if (message.taxAmount !== 0)
            writer.tag(36, WireType.Bit64).double(message.taxAmount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message order.OrderResponse
 */
export const OrderResponse = new OrderResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CancelOrderRequest$Type extends MessageType<CancelOrderRequest> {
    constructor() {
        super("order.CancelOrderRequest", [
            { no: 1, name: "order_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CancelOrderRequest>): CancelOrderRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.orderCode = "";
        message.reason = "";
        message.sessionId = "";
        if (value !== undefined)
            reflectionMergePartial<CancelOrderRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CancelOrderRequest): CancelOrderRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string order_code */ 1:
                    message.orderCode = reader.string();
                    break;
                case /* string reason */ 2:
                    message.reason = reader.string();
                    break;
                case /* string session_id */ 3:
                    message.sessionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CancelOrderRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string order_code = 1; */
        if (message.orderCode !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.orderCode);
        /* string reason = 2; */
        if (message.reason !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.reason);
        /* string session_id = 3; */
        if (message.sessionId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.sessionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message order.CancelOrderRequest
 */
export const CancelOrderRequest = new CancelOrderRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOrderRequest$Type extends MessageType<GetOrderRequest> {
    constructor() {
        super("order.GetOrderRequest", [
            { no: 1, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetOrderRequest>): GetOrderRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slug = "";
        message.sessionId = "";
        if (value !== undefined)
            reflectionMergePartial<GetOrderRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetOrderRequest): GetOrderRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string slug */ 1:
                    message.slug = reader.string();
                    break;
                case /* string session_id */ 2:
                    message.sessionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetOrderRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string slug = 1; */
        if (message.slug !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.slug);
        /* string session_id = 2; */
        if (message.sessionId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.sessionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message order.GetOrderRequest
 */
export const GetOrderRequest = new GetOrderRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOrderTrackingResponse$Type extends MessageType<GetOrderTrackingResponse> {
    constructor() {
        super("order.GetOrderTrackingResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "tracking_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "carrier", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "carrier_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "estimated_from", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 6, name: "estimated_to", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 7, name: "events", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TrackingEvent },
            { no: 8, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetOrderTrackingResponse>): GetOrderTrackingResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.trackingCode = "";
        message.carrier = "";
        message.carrierUrl = "";
        message.estimatedFrom = 0n;
        message.estimatedTo = 0n;
        message.events = [];
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<GetOrderTrackingResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetOrderTrackingResponse): GetOrderTrackingResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string tracking_code */ 2:
                    message.trackingCode = reader.string();
                    break;
                case /* string carrier */ 3:
                    message.carrier = reader.string();
                    break;
                case /* string carrier_url */ 4:
                    message.carrierUrl = reader.string();
                    break;
                case /* int64 estimated_from */ 5:
                    message.estimatedFrom = reader.int64().toBigInt();
                    break;
                case /* int64 estimated_to */ 6:
                    message.estimatedTo = reader.int64().toBigInt();
                    break;
                case /* repeated order.TrackingEvent events */ 7:
                    message.events.push(TrackingEvent.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string message */ 8:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetOrderTrackingResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string tracking_code = 2; */
        if (message.trackingCode !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.trackingCode);
        /* string carrier = 3; */
        if (message.carrier !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.carrier);
        /* string carrier_url = 4; */
        if (message.carrierUrl !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.carrierUrl);
        /* int64 estimated_from = 5; */
        if (message.estimatedFrom !== 0n)
            writer.tag(5, WireType.Varint).int64(message.estimatedFrom);
        /* int64 estimated_to = 6; */
        if (message.estimatedTo !== 0n)
            writer.tag(6, WireType.Varint).int64(message.estimatedTo);
        /* repeated order.TrackingEvent events = 7; */
        for (let i = 0; i < message.events.length; i++)
            TrackingEvent.internalBinaryWrite(message.events[i], writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* string message = 8; */
        if (message.message !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message order.GetOrderTrackingResponse
 */
export const GetOrderTrackingResponse = new GetOrderTrackingResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TrackingEvent$Type extends MessageType<TrackingEvent> {
    constructor() {
        super("order.TrackingEvent", [
            { no: 1, name: "event_time", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "location", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "is_current", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<TrackingEvent>): TrackingEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventTime = 0n;
        message.location = "";
        message.description = "";
        message.status = "";
        message.isCurrent = false;
        if (value !== undefined)
            reflectionMergePartial<TrackingEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TrackingEvent): TrackingEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 event_time */ 1:
                    message.eventTime = reader.int64().toBigInt();
                    break;
                case /* string location */ 2:
                    message.location = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* string status */ 4:
                    message.status = reader.string();
                    break;
                case /* bool is_current */ 5:
                    message.isCurrent = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TrackingEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 event_time = 1; */
        if (message.eventTime !== 0n)
            writer.tag(1, WireType.Varint).int64(message.eventTime);
        /* string location = 2; */
        if (message.location !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.location);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* string status = 4; */
        if (message.status !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.status);
        /* bool is_current = 5; */
        if (message.isCurrent !== false)
            writer.tag(5, WireType.Varint).bool(message.isCurrent);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message order.TrackingEvent
 */
export const TrackingEvent = new TrackingEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OrderDetailResponse$Type extends MessageType<OrderDetailResponse> {
    constructor() {
        super("order.OrderDetailResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "order", kind: "message", T: () => OrderResponse },
            { no: 4, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => OrderItemResponse }
        ]);
    }
    create(value?: PartialMessage<OrderDetailResponse>): OrderDetailResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<OrderDetailResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OrderDetailResponse): OrderDetailResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* order.OrderResponse order */ 3:
                    message.order = OrderResponse.internalBinaryRead(reader, reader.uint32(), options, message.order);
                    break;
                case /* repeated order.OrderItemResponse items */ 4:
                    message.items.push(OrderItemResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OrderDetailResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* order.OrderResponse order = 3; */
        if (message.order)
            OrderResponse.internalBinaryWrite(message.order, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* repeated order.OrderItemResponse items = 4; */
        for (let i = 0; i < message.items.length; i++)
            OrderItemResponse.internalBinaryWrite(message.items[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message order.OrderDetailResponse
 */
export const OrderDetailResponse = new OrderDetailResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OrderItemResponse$Type extends MessageType<OrderItemResponse> {
    constructor() {
        super("order.OrderItemResponse", [
            { no: 1, name: "product_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "variant_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "price", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "qty", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "image_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "sub_total", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<OrderItemResponse>): OrderItemResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.productName = "";
        message.variantName = "";
        message.price = 0;
        message.qty = 0;
        message.imageUrl = "";
        message.subTotal = 0;
        if (value !== undefined)
            reflectionMergePartial<OrderItemResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OrderItemResponse): OrderItemResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string product_name */ 1:
                    message.productName = reader.string();
                    break;
                case /* string variant_name */ 2:
                    message.variantName = reader.string();
                    break;
                case /* double price */ 3:
                    message.price = reader.double();
                    break;
                case /* int32 qty */ 4:
                    message.qty = reader.int32();
                    break;
                case /* string image_url */ 5:
                    message.imageUrl = reader.string();
                    break;
                case /* double sub_total */ 6:
                    message.subTotal = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OrderItemResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string product_name = 1; */
        if (message.productName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.productName);
        /* string variant_name = 2; */
        if (message.variantName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.variantName);
        /* double price = 3; */
        if (message.price !== 0)
            writer.tag(3, WireType.Bit64).double(message.price);
        /* int32 qty = 4; */
        if (message.qty !== 0)
            writer.tag(4, WireType.Varint).int32(message.qty);
        /* string image_url = 5; */
        if (message.imageUrl !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.imageUrl);
        /* double sub_total = 6; */
        if (message.subTotal !== 0)
            writer.tag(6, WireType.Bit64).double(message.subTotal);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message order.OrderItemResponse
 */
export const OrderItemResponse = new OrderItemResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RequestRefundRequest$Type extends MessageType<RequestRefundRequest> {
    constructor() {
        super("order.RequestRefundRequest", [
            { no: 1, name: "order_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "refund_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "amount", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "evidence_urls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RequestRefundRequest>): RequestRefundRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.orderCode = "";
        message.reason = "";
        message.refundType = "";
        message.amount = 0;
        message.evidenceUrls = [];
        message.sessionId = "";
        if (value !== undefined)
            reflectionMergePartial<RequestRefundRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RequestRefundRequest): RequestRefundRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string order_code */ 1:
                    message.orderCode = reader.string();
                    break;
                case /* string reason */ 2:
                    message.reason = reader.string();
                    break;
                case /* string refund_type */ 3:
                    message.refundType = reader.string();
                    break;
                case /* double amount */ 4:
                    message.amount = reader.double();
                    break;
                case /* repeated string evidence_urls */ 5:
                    message.evidenceUrls.push(reader.string());
                    break;
                case /* string session_id */ 6:
                    message.sessionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RequestRefundRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string order_code = 1; */
        if (message.orderCode !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.orderCode);
        /* string reason = 2; */
        if (message.reason !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.reason);
        /* string refund_type = 3; */
        if (message.refundType !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.refundType);
        /* double amount = 4; */
        if (message.amount !== 0)
            writer.tag(4, WireType.Bit64).double(message.amount);
        /* repeated string evidence_urls = 5; */
        for (let i = 0; i < message.evidenceUrls.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.evidenceUrls[i]);
        /* string session_id = 6; */
        if (message.sessionId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.sessionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message order.RequestRefundRequest
 */
export const RequestRefundRequest = new RequestRefundRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubmitReviewRequest$Type extends MessageType<SubmitReviewRequest> {
    constructor() {
        super("order.SubmitReviewRequest", [
            { no: 1, name: "order_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "order_item_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "rating", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "comment", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "media_urls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "is_anonymous", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SubmitReviewRequest>): SubmitReviewRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.orderId = "";
        message.orderItemId = "";
        message.rating = 0;
        message.comment = "";
        message.mediaUrls = [];
        message.isAnonymous = false;
        message.sessionId = "";
        if (value !== undefined)
            reflectionMergePartial<SubmitReviewRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubmitReviewRequest): SubmitReviewRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string order_id */ 1:
                    message.orderId = reader.string();
                    break;
                case /* string order_item_id */ 2:
                    message.orderItemId = reader.string();
                    break;
                case /* int32 rating */ 3:
                    message.rating = reader.int32();
                    break;
                case /* string comment */ 4:
                    message.comment = reader.string();
                    break;
                case /* repeated string media_urls */ 5:
                    message.mediaUrls.push(reader.string());
                    break;
                case /* bool is_anonymous */ 6:
                    message.isAnonymous = reader.bool();
                    break;
                case /* string session_id */ 7:
                    message.sessionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SubmitReviewRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string order_id = 1; */
        if (message.orderId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.orderId);
        /* string order_item_id = 2; */
        if (message.orderItemId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.orderItemId);
        /* int32 rating = 3; */
        if (message.rating !== 0)
            writer.tag(3, WireType.Varint).int32(message.rating);
        /* string comment = 4; */
        if (message.comment !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.comment);
        /* repeated string media_urls = 5; */
        for (let i = 0; i < message.mediaUrls.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.mediaUrls[i]);
        /* bool is_anonymous = 6; */
        if (message.isAnonymous !== false)
            writer.tag(6, WireType.Varint).bool(message.isAnonymous);
        /* string session_id = 7; */
        if (message.sessionId !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.sessionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message order.SubmitReviewRequest
 */
export const SubmitReviewRequest = new SubmitReviewRequest$Type();
/**
 * @generated ServiceType for protobuf service order.OrderService
 */
export const OrderService = new ServiceType("order.OrderService", [
    { name: "PlaceOrder", options: {}, I: PlaceOrderRequest, O: OperationResult },
    { name: "GetMyOrders", options: {}, I: CommonQuery, O: GetOrdersResponse },
    { name: "GetOrderDetail", options: {}, I: GetOrderRequest, O: OrderDetailResponse },
    { name: "CancelOrder", options: {}, I: CancelOrderRequest, O: OperationResult },
    { name: "GetOrderTracking", options: {}, I: GetOrderRequest, O: GetOrderTrackingResponse },
    { name: "RequestRefund", options: {}, I: RequestRefundRequest, O: OperationResult },
    { name: "SubmitReview", options: {}, I: SubmitReviewRequest, O: OperationResult }
]);
