// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/page_view.proto" (package "page_view", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PageViewService } from "./page_view";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { PageViewResponse } from "./page_view";
import type { GetPageViewRequest } from "./page_view";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service page_view.PageViewService
 */
export interface IPageViewServiceClient {
    /**
     * @generated from protobuf rpc: GetPageView
     */
    getPageView(input: GetPageViewRequest, options?: RpcOptions): UnaryCall<GetPageViewRequest, PageViewResponse>;
}
/**
 * @generated from protobuf service page_view.PageViewService
 */
export class PageViewServiceClient implements IPageViewServiceClient, ServiceInfo {
    typeName = PageViewService.typeName;
    methods = PageViewService.methods;
    options = PageViewService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetPageView
     */
    getPageView(input: GetPageViewRequest, options?: RpcOptions): UnaryCall<GetPageViewRequest, PageViewResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPageViewRequest, PageViewResponse>("unary", this._transport, method, opt, input);
    }
}
