// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/page_view.proto" (package "page_view", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message page_view.GetPageViewRequest
 */
export interface GetPageViewRequest {
    /**
     * @generated from protobuf field: string ref = 1
     */
    ref: string;
}
/**
 * @generated from protobuf message page_view.PageViewResponse
 */
export interface PageViewResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: page_view.PageViewData data = 3
     */
    data?: PageViewData;
}
/**
 * @generated from protobuf message page_view.PageViewData
 */
export interface PageViewData {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: repeated string ref_id = 2
     */
    refId: string[];
    /**
     * @generated from protobuf field: repeated string ref_slug = 3
     */
    refSlug: string[];
    /**
     * @generated from protobuf field: string config = 4
     */
    config: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetPageViewRequest$Type extends MessageType<GetPageViewRequest> {
    constructor() {
        super("page_view.GetPageViewRequest", [
            { no: 1, name: "ref", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetPageViewRequest>): GetPageViewRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ref = "";
        if (value !== undefined)
            reflectionMergePartial<GetPageViewRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPageViewRequest): GetPageViewRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string ref */ 1:
                    message.ref = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPageViewRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string ref = 1; */
        if (message.ref !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.ref);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message page_view.GetPageViewRequest
 */
export const GetPageViewRequest = new GetPageViewRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PageViewResponse$Type extends MessageType<PageViewResponse> {
    constructor() {
        super("page_view.PageViewResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "message", T: () => PageViewData }
        ]);
    }
    create(value?: PartialMessage<PageViewResponse>): PageViewResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<PageViewResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageViewResponse): PageViewResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* page_view.PageViewData data */ 3:
                    message.data = PageViewData.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageViewResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* page_view.PageViewData data = 3; */
        if (message.data)
            PageViewData.internalBinaryWrite(message.data, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message page_view.PageViewResponse
 */
export const PageViewResponse = new PageViewResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PageViewData$Type extends MessageType<PageViewData> {
    constructor() {
        super("page_view.PageViewData", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "ref_id", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "ref_slug", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "config", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PageViewData>): PageViewData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.refId = [];
        message.refSlug = [];
        message.config = "";
        if (value !== undefined)
            reflectionMergePartial<PageViewData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageViewData): PageViewData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* repeated string ref_id */ 2:
                    message.refId.push(reader.string());
                    break;
                case /* repeated string ref_slug */ 3:
                    message.refSlug.push(reader.string());
                    break;
                case /* string config */ 4:
                    message.config = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageViewData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* repeated string ref_id = 2; */
        for (let i = 0; i < message.refId.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.refId[i]);
        /* repeated string ref_slug = 3; */
        for (let i = 0; i < message.refSlug.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.refSlug[i]);
        /* string config = 4; */
        if (message.config !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.config);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message page_view.PageViewData
 */
export const PageViewData = new PageViewData$Type();
/**
 * @generated ServiceType for protobuf service page_view.PageViewService
 */
export const PageViewService = new ServiceType("page_view.PageViewService", [
    { name: "GetPageView", options: {}, I: GetPageViewRequest, O: PageViewResponse }
]);
