// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/product.proto" (package "product", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ProductService } from "./product";
import type { ProductGroupDataSourceResponse } from "./product";
import type { ProductGroupResponseWrapped } from "./product";
import type { GetBySlugPagedRequest } from "./common";
import type { ProductResponseWrapped } from "./product";
import type { GetBySlugRequest } from "./common";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ProductDataSourceResponse } from "./product";
import type { CommonQuery } from "./common";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service product.ProductService
 */
export interface IProductServiceClient {
    /**
     * @generated from protobuf rpc: GetProductsByQuery
     */
    getProductsByQuery(input: CommonQuery, options?: RpcOptions): UnaryCall<CommonQuery, ProductDataSourceResponse>;
    /**
     * @generated from protobuf rpc: GetProductDetail
     */
    getProductDetail(input: GetBySlugRequest, options?: RpcOptions): UnaryCall<GetBySlugRequest, ProductResponseWrapped>;
    /**
     * @generated from protobuf rpc: GetProductsByProductGroupSlug
     */
    getProductsByProductGroupSlug(input: GetBySlugPagedRequest, options?: RpcOptions): UnaryCall<GetBySlugPagedRequest, ProductDataSourceResponse>;
    /**
     * @generated from protobuf rpc: GetProductGroupsBySlug
     */
    getProductGroupsBySlug(input: GetBySlugRequest, options?: RpcOptions): UnaryCall<GetBySlugRequest, ProductGroupResponseWrapped>;
    /**
     * @generated from protobuf rpc: GetProductGroupsByQuery
     */
    getProductGroupsByQuery(input: CommonQuery, options?: RpcOptions): UnaryCall<CommonQuery, ProductGroupDataSourceResponse>;
}
/**
 * @generated from protobuf service product.ProductService
 */
export class ProductServiceClient implements IProductServiceClient, ServiceInfo {
    typeName = ProductService.typeName;
    methods = ProductService.methods;
    options = ProductService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetProductsByQuery
     */
    getProductsByQuery(input: CommonQuery, options?: RpcOptions): UnaryCall<CommonQuery, ProductDataSourceResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CommonQuery, ProductDataSourceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetProductDetail
     */
    getProductDetail(input: GetBySlugRequest, options?: RpcOptions): UnaryCall<GetBySlugRequest, ProductResponseWrapped> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBySlugRequest, ProductResponseWrapped>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetProductsByProductGroupSlug
     */
    getProductsByProductGroupSlug(input: GetBySlugPagedRequest, options?: RpcOptions): UnaryCall<GetBySlugPagedRequest, ProductDataSourceResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBySlugPagedRequest, ProductDataSourceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetProductGroupsBySlug
     */
    getProductGroupsBySlug(input: GetBySlugRequest, options?: RpcOptions): UnaryCall<GetBySlugRequest, ProductGroupResponseWrapped> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBySlugRequest, ProductGroupResponseWrapped>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetProductGroupsByQuery
     */
    getProductGroupsByQuery(input: CommonQuery, options?: RpcOptions): UnaryCall<CommonQuery, ProductGroupDataSourceResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<CommonQuery, ProductGroupDataSourceResponse>("unary", this._transport, method, opt, input);
    }
}
