// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/product.proto" (package "product", syntax proto3)
// tslint:disable
import { GetBySlugPagedRequest } from "./common";
import { GetBySlugRequest } from "./common";
import { CommonQuery } from "./common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
import { CommonDataSourceMeta } from "./common";
/**
 * @generated from protobuf message product.ProductResponseWrapped
 */
export interface ProductResponseWrapped {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: product.ProductResponse data = 3
     */
    data?: ProductResponse;
}
/**
 * @generated from protobuf message product.ProductDataSourceResponse
 */
export interface ProductDataSourceResponse {
    /**
     * @generated from protobuf field: common.CommonDataSourceMeta meta = 1
     */
    meta?: CommonDataSourceMeta;
    /**
     * @generated from protobuf field: repeated product.ProductResponse data = 2
     */
    data: ProductResponse[];
}
/**
 * @generated from protobuf message product.ProductGroupResponseWrapped
 */
export interface ProductGroupResponseWrapped {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: product.ProductGroupResponse data = 3
     */
    data?: ProductGroupResponse;
}
/**
 * @generated from protobuf message product.ProductGroupDataSourceResponse
 */
export interface ProductGroupDataSourceResponse {
    /**
     * @generated from protobuf field: common.CommonDataSourceMeta meta = 1
     */
    meta?: CommonDataSourceMeta;
    /**
     * @generated from protobuf field: repeated product.ProductGroupResponse data = 2
     */
    data: ProductGroupResponse[];
}
/**
 * @generated from protobuf message product.ProductVariantResponse
 */
export interface ProductVariantResponse {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string sku = 2
     */
    sku: string;
    /**
     * @generated from protobuf field: string barcode = 3
     */
    barcode: string;
    /**
     * @generated from protobuf field: double price = 4
     */
    price: number;
    /**
     * @generated from protobuf field: double compare_price = 5
     */
    comparePrice: number;
    /**
     * @generated from protobuf field: int32 stock = 6
     */
    stock: number;
    /**
     * @generated from protobuf field: string attributes_name1 = 7
     */
    attributesName1: string;
    /**
     * @generated from protobuf field: string attributes_value1 = 8
     */
    attributesValue1: string;
    /**
     * @generated from protobuf field: string attributes_name2 = 9
     */
    attributesName2: string;
    /**
     * @generated from protobuf field: string attributes_value2 = 10
     */
    attributesValue2: string;
    /**
     * @generated from protobuf field: string attributes_name3 = 11
     */
    attributesName3: string;
    /**
     * @generated from protobuf field: string attributes_value3 = 12
     */
    attributesValue3: string;
    /**
     * @generated from protobuf field: string image = 13
     */
    image: string;
    /**
     * @generated from protobuf field: string product_sku = 14
     */
    productSku: string;
    /**
     * @generated from protobuf field: string product_id = 15
     */
    productId: string;
    /**
     * @generated from protobuf field: string variant_name = 16
     */
    variantName: string;
}
/**
 * @generated from protobuf message product.ProductVariantConfigResponse
 */
export interface ProductVariantConfigResponse {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: repeated string values = 2
     */
    values: string[];
}
/**
 * @generated from protobuf message product.ProductResponse
 */
export interface ProductResponse {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string;
    /**
     * @generated from protobuf field: double price = 4
     */
    price: number;
    /**
     * @generated from protobuf field: int32 stock = 5
     */
    stock: number;
    /**
     * @generated from protobuf field: string category_id = 6
     */
    categoryId: string;
    /**
     * @generated from protobuf field: string category_name = 7
     */
    categoryName: string;
    /**
     * @generated from protobuf field: bool is_active = 8
     */
    isActive: boolean;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 9
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 10
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: string img_url = 11
     */
    imgUrl: string;
    /**
     * @generated from protobuf field: string slug = 12
     */
    slug: string;
    /**
     * @generated from protobuf field: repeated string image_urls = 13
     */
    imageUrls: string[];
    /**
     * @generated from protobuf field: string sku = 14
     */
    sku: string;
    /**
     * @generated from protobuf field: string barcode = 15
     */
    barcode: string;
    /**
     * @generated from protobuf field: string classify = 16
     */
    classify: string;
    /**
     * @generated from protobuf field: double compare_price = 17
     */
    comparePrice: number;
    /**
     * @generated from protobuf field: double weight = 18
     */
    weight: number;
    /**
     * @generated from protobuf field: bool tax_included = 19
     */
    taxIncluded: boolean;
    /**
     * @generated from protobuf field: bool track_inventory = 20
     */
    trackInventory: boolean;
    /**
     * @generated from protobuf field: string brand = 21
     */
    brand: string;
    /**
     * @generated from protobuf field: string product_spec = 22
     */
    productSpec: string;
    /**
     * @generated from protobuf field: repeated product.ProductVariantResponse variants = 26
     */
    variants: ProductVariantResponse[];
    /**
     * @generated from protobuf field: repeated product.ProductVariantConfigResponse variant_config = 27
     */
    variantConfig: ProductVariantConfigResponse[];
    /**
     * @generated from protobuf field: string org_id = 28
     */
    orgId: string;
    /**
     * @generated from protobuf field: string created_by = 29
     */
    createdBy: string;
    /**
     * @generated from protobuf field: string updated_by = 30
     */
    updatedBy: string;
    /**
     * @generated from protobuf field: map<string, string> extend_object = 31
     */
    extendObject: {
        [key: string]: string;
    };
}
/**
 * @generated from protobuf message product.ProductGroupResponse
 */
export interface ProductGroupResponse {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string slug = 3
     */
    slug: string;
    /**
     * @generated from protobuf field: string description = 4
     */
    description: string;
    /**
     * @generated from protobuf field: string image = 5
     */
    image: string;
    /**
     * @generated from protobuf field: string group_by = 6
     */
    groupBy: string;
    /**
     * @generated from protobuf field: string operator = 7
     */
    operator: string;
    /**
     * @generated from protobuf field: string status = 8
     */
    status: string;
    /**
     * @generated from protobuf field: repeated string product_ids = 9
     */
    productIds: string[];
    /**
     * @generated from protobuf field: repeated product.ProductResponse products = 10
     */
    products: ProductResponse[];
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 11
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 12
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: string org_id = 13
     */
    orgId: string;
    /**
     * @generated from protobuf field: string created_by = 14
     */
    createdBy: string;
    /**
     * @generated from protobuf field: string updated_by = 15
     */
    updatedBy: string;
    /**
     * @generated from protobuf field: map<string, string> extend_object = 16
     */
    extendObject: {
        [key: string]: string;
    };
}
// @generated message type with reflection information, may provide speed optimized methods
class ProductResponseWrapped$Type extends MessageType<ProductResponseWrapped> {
    constructor() {
        super("product.ProductResponseWrapped", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "message", T: () => ProductResponse }
        ]);
    }
    create(value?: PartialMessage<ProductResponseWrapped>): ProductResponseWrapped {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<ProductResponseWrapped>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProductResponseWrapped): ProductResponseWrapped {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* product.ProductResponse data */ 3:
                    message.data = ProductResponse.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProductResponseWrapped, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* product.ProductResponse data = 3; */
        if (message.data)
            ProductResponse.internalBinaryWrite(message.data, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.ProductResponseWrapped
 */
export const ProductResponseWrapped = new ProductResponseWrapped$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProductDataSourceResponse$Type extends MessageType<ProductDataSourceResponse> {
    constructor() {
        super("product.ProductDataSourceResponse", [
            { no: 1, name: "meta", kind: "message", T: () => CommonDataSourceMeta },
            { no: 2, name: "data", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ProductResponse }
        ]);
    }
    create(value?: PartialMessage<ProductDataSourceResponse>): ProductDataSourceResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = [];
        if (value !== undefined)
            reflectionMergePartial<ProductDataSourceResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProductDataSourceResponse): ProductDataSourceResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.CommonDataSourceMeta meta */ 1:
                    message.meta = CommonDataSourceMeta.internalBinaryRead(reader, reader.uint32(), options, message.meta);
                    break;
                case /* repeated product.ProductResponse data */ 2:
                    message.data.push(ProductResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProductDataSourceResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.CommonDataSourceMeta meta = 1; */
        if (message.meta)
            CommonDataSourceMeta.internalBinaryWrite(message.meta, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated product.ProductResponse data = 2; */
        for (let i = 0; i < message.data.length; i++)
            ProductResponse.internalBinaryWrite(message.data[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.ProductDataSourceResponse
 */
export const ProductDataSourceResponse = new ProductDataSourceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProductGroupResponseWrapped$Type extends MessageType<ProductGroupResponseWrapped> {
    constructor() {
        super("product.ProductGroupResponseWrapped", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "message", T: () => ProductGroupResponse }
        ]);
    }
    create(value?: PartialMessage<ProductGroupResponseWrapped>): ProductGroupResponseWrapped {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<ProductGroupResponseWrapped>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProductGroupResponseWrapped): ProductGroupResponseWrapped {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* product.ProductGroupResponse data */ 3:
                    message.data = ProductGroupResponse.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProductGroupResponseWrapped, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* product.ProductGroupResponse data = 3; */
        if (message.data)
            ProductGroupResponse.internalBinaryWrite(message.data, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.ProductGroupResponseWrapped
 */
export const ProductGroupResponseWrapped = new ProductGroupResponseWrapped$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProductGroupDataSourceResponse$Type extends MessageType<ProductGroupDataSourceResponse> {
    constructor() {
        super("product.ProductGroupDataSourceResponse", [
            { no: 1, name: "meta", kind: "message", T: () => CommonDataSourceMeta },
            { no: 2, name: "data", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ProductGroupResponse }
        ]);
    }
    create(value?: PartialMessage<ProductGroupDataSourceResponse>): ProductGroupDataSourceResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = [];
        if (value !== undefined)
            reflectionMergePartial<ProductGroupDataSourceResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProductGroupDataSourceResponse): ProductGroupDataSourceResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.CommonDataSourceMeta meta */ 1:
                    message.meta = CommonDataSourceMeta.internalBinaryRead(reader, reader.uint32(), options, message.meta);
                    break;
                case /* repeated product.ProductGroupResponse data */ 2:
                    message.data.push(ProductGroupResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProductGroupDataSourceResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.CommonDataSourceMeta meta = 1; */
        if (message.meta)
            CommonDataSourceMeta.internalBinaryWrite(message.meta, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated product.ProductGroupResponse data = 2; */
        for (let i = 0; i < message.data.length; i++)
            ProductGroupResponse.internalBinaryWrite(message.data[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.ProductGroupDataSourceResponse
 */
export const ProductGroupDataSourceResponse = new ProductGroupDataSourceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProductVariantResponse$Type extends MessageType<ProductVariantResponse> {
    constructor() {
        super("product.ProductVariantResponse", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "sku", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "barcode", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "price", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "compare_price", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "stock", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "attributes_name1", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "attributes_value1", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "attributes_name2", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "attributes_value2", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "attributes_name3", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "attributes_value3", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "image", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "product_sku", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "product_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "variant_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ProductVariantResponse>): ProductVariantResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.sku = "";
        message.barcode = "";
        message.price = 0;
        message.comparePrice = 0;
        message.stock = 0;
        message.attributesName1 = "";
        message.attributesValue1 = "";
        message.attributesName2 = "";
        message.attributesValue2 = "";
        message.attributesName3 = "";
        message.attributesValue3 = "";
        message.image = "";
        message.productSku = "";
        message.productId = "";
        message.variantName = "";
        if (value !== undefined)
            reflectionMergePartial<ProductVariantResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProductVariantResponse): ProductVariantResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string sku */ 2:
                    message.sku = reader.string();
                    break;
                case /* string barcode */ 3:
                    message.barcode = reader.string();
                    break;
                case /* double price */ 4:
                    message.price = reader.double();
                    break;
                case /* double compare_price */ 5:
                    message.comparePrice = reader.double();
                    break;
                case /* int32 stock */ 6:
                    message.stock = reader.int32();
                    break;
                case /* string attributes_name1 */ 7:
                    message.attributesName1 = reader.string();
                    break;
                case /* string attributes_value1 */ 8:
                    message.attributesValue1 = reader.string();
                    break;
                case /* string attributes_name2 */ 9:
                    message.attributesName2 = reader.string();
                    break;
                case /* string attributes_value2 */ 10:
                    message.attributesValue2 = reader.string();
                    break;
                case /* string attributes_name3 */ 11:
                    message.attributesName3 = reader.string();
                    break;
                case /* string attributes_value3 */ 12:
                    message.attributesValue3 = reader.string();
                    break;
                case /* string image */ 13:
                    message.image = reader.string();
                    break;
                case /* string product_sku */ 14:
                    message.productSku = reader.string();
                    break;
                case /* string product_id */ 15:
                    message.productId = reader.string();
                    break;
                case /* string variant_name */ 16:
                    message.variantName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProductVariantResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string sku = 2; */
        if (message.sku !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.sku);
        /* string barcode = 3; */
        if (message.barcode !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.barcode);
        /* double price = 4; */
        if (message.price !== 0)
            writer.tag(4, WireType.Bit64).double(message.price);
        /* double compare_price = 5; */
        if (message.comparePrice !== 0)
            writer.tag(5, WireType.Bit64).double(message.comparePrice);
        /* int32 stock = 6; */
        if (message.stock !== 0)
            writer.tag(6, WireType.Varint).int32(message.stock);
        /* string attributes_name1 = 7; */
        if (message.attributesName1 !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.attributesName1);
        /* string attributes_value1 = 8; */
        if (message.attributesValue1 !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.attributesValue1);
        /* string attributes_name2 = 9; */
        if (message.attributesName2 !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.attributesName2);
        /* string attributes_value2 = 10; */
        if (message.attributesValue2 !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.attributesValue2);
        /* string attributes_name3 = 11; */
        if (message.attributesName3 !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.attributesName3);
        /* string attributes_value3 = 12; */
        if (message.attributesValue3 !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.attributesValue3);
        /* string image = 13; */
        if (message.image !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.image);
        /* string product_sku = 14; */
        if (message.productSku !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.productSku);
        /* string product_id = 15; */
        if (message.productId !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.productId);
        /* string variant_name = 16; */
        if (message.variantName !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.variantName);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.ProductVariantResponse
 */
export const ProductVariantResponse = new ProductVariantResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProductVariantConfigResponse$Type extends MessageType<ProductVariantConfigResponse> {
    constructor() {
        super("product.ProductVariantConfigResponse", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "values", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ProductVariantConfigResponse>): ProductVariantConfigResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.values = [];
        if (value !== undefined)
            reflectionMergePartial<ProductVariantConfigResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProductVariantConfigResponse): ProductVariantConfigResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* repeated string values */ 2:
                    message.values.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProductVariantConfigResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* repeated string values = 2; */
        for (let i = 0; i < message.values.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.values[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.ProductVariantConfigResponse
 */
export const ProductVariantConfigResponse = new ProductVariantConfigResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProductResponse$Type extends MessageType<ProductResponse> {
    constructor() {
        super("product.ProductResponse", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "price", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "stock", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "category_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "category_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "is_active", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 9, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 10, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 11, name: "img_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "image_urls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "sku", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "barcode", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "classify", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "compare_price", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 18, name: "weight", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 19, name: "tax_included", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 20, name: "track_inventory", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 21, name: "brand", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 22, name: "product_spec", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 26, name: "variants", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ProductVariantResponse },
            { no: 27, name: "variant_config", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ProductVariantConfigResponse },
            { no: 28, name: "org_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 29, name: "created_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 30, name: "updated_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 31, name: "extend_object", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
    create(value?: PartialMessage<ProductResponse>): ProductResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.description = "";
        message.price = 0;
        message.stock = 0;
        message.categoryId = "";
        message.categoryName = "";
        message.isActive = false;
        message.imgUrl = "";
        message.slug = "";
        message.imageUrls = [];
        message.sku = "";
        message.barcode = "";
        message.classify = "";
        message.comparePrice = 0;
        message.weight = 0;
        message.taxIncluded = false;
        message.trackInventory = false;
        message.brand = "";
        message.productSpec = "";
        message.variants = [];
        message.variantConfig = [];
        message.orgId = "";
        message.createdBy = "";
        message.updatedBy = "";
        message.extendObject = {};
        if (value !== undefined)
            reflectionMergePartial<ProductResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProductResponse): ProductResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* double price */ 4:
                    message.price = reader.double();
                    break;
                case /* int32 stock */ 5:
                    message.stock = reader.int32();
                    break;
                case /* string category_id */ 6:
                    message.categoryId = reader.string();
                    break;
                case /* string category_name */ 7:
                    message.categoryName = reader.string();
                    break;
                case /* bool is_active */ 8:
                    message.isActive = reader.bool();
                    break;
                case /* google.protobuf.Timestamp created_at */ 9:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 10:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* string img_url */ 11:
                    message.imgUrl = reader.string();
                    break;
                case /* string slug */ 12:
                    message.slug = reader.string();
                    break;
                case /* repeated string image_urls */ 13:
                    message.imageUrls.push(reader.string());
                    break;
                case /* string sku */ 14:
                    message.sku = reader.string();
                    break;
                case /* string barcode */ 15:
                    message.barcode = reader.string();
                    break;
                case /* string classify */ 16:
                    message.classify = reader.string();
                    break;
                case /* double compare_price */ 17:
                    message.comparePrice = reader.double();
                    break;
                case /* double weight */ 18:
                    message.weight = reader.double();
                    break;
                case /* bool tax_included */ 19:
                    message.taxIncluded = reader.bool();
                    break;
                case /* bool track_inventory */ 20:
                    message.trackInventory = reader.bool();
                    break;
                case /* string brand */ 21:
                    message.brand = reader.string();
                    break;
                case /* string product_spec */ 22:
                    message.productSpec = reader.string();
                    break;
                case /* repeated product.ProductVariantResponse variants */ 26:
                    message.variants.push(ProductVariantResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated product.ProductVariantConfigResponse variant_config */ 27:
                    message.variantConfig.push(ProductVariantConfigResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string org_id */ 28:
                    message.orgId = reader.string();
                    break;
                case /* string created_by */ 29:
                    message.createdBy = reader.string();
                    break;
                case /* string updated_by */ 30:
                    message.updatedBy = reader.string();
                    break;
                case /* map<string, string> extend_object */ 31:
                    this.binaryReadMap31(message.extendObject, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap31(map: ProductResponse["extendObject"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof ProductResponse["extendObject"] | undefined, val: ProductResponse["extendObject"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for product.ProductResponse.extend_object");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: ProductResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* double price = 4; */
        if (message.price !== 0)
            writer.tag(4, WireType.Bit64).double(message.price);
        /* int32 stock = 5; */
        if (message.stock !== 0)
            writer.tag(5, WireType.Varint).int32(message.stock);
        /* string category_id = 6; */
        if (message.categoryId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.categoryId);
        /* string category_name = 7; */
        if (message.categoryName !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.categoryName);
        /* bool is_active = 8; */
        if (message.isActive !== false)
            writer.tag(8, WireType.Varint).bool(message.isActive);
        /* google.protobuf.Timestamp created_at = 9; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 10; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* string img_url = 11; */
        if (message.imgUrl !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.imgUrl);
        /* string slug = 12; */
        if (message.slug !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.slug);
        /* repeated string image_urls = 13; */
        for (let i = 0; i < message.imageUrls.length; i++)
            writer.tag(13, WireType.LengthDelimited).string(message.imageUrls[i]);
        /* string sku = 14; */
        if (message.sku !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.sku);
        /* string barcode = 15; */
        if (message.barcode !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.barcode);
        /* string classify = 16; */
        if (message.classify !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.classify);
        /* double compare_price = 17; */
        if (message.comparePrice !== 0)
            writer.tag(17, WireType.Bit64).double(message.comparePrice);
        /* double weight = 18; */
        if (message.weight !== 0)
            writer.tag(18, WireType.Bit64).double(message.weight);
        /* bool tax_included = 19; */
        if (message.taxIncluded !== false)
            writer.tag(19, WireType.Varint).bool(message.taxIncluded);
        /* bool track_inventory = 20; */
        if (message.trackInventory !== false)
            writer.tag(20, WireType.Varint).bool(message.trackInventory);
        /* string brand = 21; */
        if (message.brand !== "")
            writer.tag(21, WireType.LengthDelimited).string(message.brand);
        /* string product_spec = 22; */
        if (message.productSpec !== "")
            writer.tag(22, WireType.LengthDelimited).string(message.productSpec);
        /* repeated product.ProductVariantResponse variants = 26; */
        for (let i = 0; i < message.variants.length; i++)
            ProductVariantResponse.internalBinaryWrite(message.variants[i], writer.tag(26, WireType.LengthDelimited).fork(), options).join();
        /* repeated product.ProductVariantConfigResponse variant_config = 27; */
        for (let i = 0; i < message.variantConfig.length; i++)
            ProductVariantConfigResponse.internalBinaryWrite(message.variantConfig[i], writer.tag(27, WireType.LengthDelimited).fork(), options).join();
        /* string org_id = 28; */
        if (message.orgId !== "")
            writer.tag(28, WireType.LengthDelimited).string(message.orgId);
        /* string created_by = 29; */
        if (message.createdBy !== "")
            writer.tag(29, WireType.LengthDelimited).string(message.createdBy);
        /* string updated_by = 30; */
        if (message.updatedBy !== "")
            writer.tag(30, WireType.LengthDelimited).string(message.updatedBy);
        /* map<string, string> extend_object = 31; */
        for (let k of globalThis.Object.keys(message.extendObject))
            writer.tag(31, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.extendObject[k]).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.ProductResponse
 */
export const ProductResponse = new ProductResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProductGroupResponse$Type extends MessageType<ProductGroupResponse> {
    constructor() {
        super("product.ProductGroupResponse", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "image", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "group_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "operator", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "product_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "products", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ProductResponse },
            { no: 11, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 12, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 13, name: "org_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "created_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "updated_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "extend_object", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
    create(value?: PartialMessage<ProductGroupResponse>): ProductGroupResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.slug = "";
        message.description = "";
        message.image = "";
        message.groupBy = "";
        message.operator = "";
        message.status = "";
        message.productIds = [];
        message.products = [];
        message.orgId = "";
        message.createdBy = "";
        message.updatedBy = "";
        message.extendObject = {};
        if (value !== undefined)
            reflectionMergePartial<ProductGroupResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProductGroupResponse): ProductGroupResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string slug */ 3:
                    message.slug = reader.string();
                    break;
                case /* string description */ 4:
                    message.description = reader.string();
                    break;
                case /* string image */ 5:
                    message.image = reader.string();
                    break;
                case /* string group_by */ 6:
                    message.groupBy = reader.string();
                    break;
                case /* string operator */ 7:
                    message.operator = reader.string();
                    break;
                case /* string status */ 8:
                    message.status = reader.string();
                    break;
                case /* repeated string product_ids */ 9:
                    message.productIds.push(reader.string());
                    break;
                case /* repeated product.ProductResponse products */ 10:
                    message.products.push(ProductResponse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* google.protobuf.Timestamp created_at */ 11:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 12:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* string org_id */ 13:
                    message.orgId = reader.string();
                    break;
                case /* string created_by */ 14:
                    message.createdBy = reader.string();
                    break;
                case /* string updated_by */ 15:
                    message.updatedBy = reader.string();
                    break;
                case /* map<string, string> extend_object */ 16:
                    this.binaryReadMap16(message.extendObject, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap16(map: ProductGroupResponse["extendObject"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof ProductGroupResponse["extendObject"] | undefined, val: ProductGroupResponse["extendObject"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for product.ProductGroupResponse.extend_object");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: ProductGroupResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string slug = 3; */
        if (message.slug !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.slug);
        /* string description = 4; */
        if (message.description !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.description);
        /* string image = 5; */
        if (message.image !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.image);
        /* string group_by = 6; */
        if (message.groupBy !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.groupBy);
        /* string operator = 7; */
        if (message.operator !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.operator);
        /* string status = 8; */
        if (message.status !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.status);
        /* repeated string product_ids = 9; */
        for (let i = 0; i < message.productIds.length; i++)
            writer.tag(9, WireType.LengthDelimited).string(message.productIds[i]);
        /* repeated product.ProductResponse products = 10; */
        for (let i = 0; i < message.products.length; i++)
            ProductResponse.internalBinaryWrite(message.products[i], writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp created_at = 11; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 12; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* string org_id = 13; */
        if (message.orgId !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.orgId);
        /* string created_by = 14; */
        if (message.createdBy !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.createdBy);
        /* string updated_by = 15; */
        if (message.updatedBy !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.updatedBy);
        /* map<string, string> extend_object = 16; */
        for (let k of globalThis.Object.keys(message.extendObject))
            writer.tag(16, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.extendObject[k]).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message product.ProductGroupResponse
 */
export const ProductGroupResponse = new ProductGroupResponse$Type();
/**
 * @generated ServiceType for protobuf service product.ProductService
 */
export const ProductService = new ServiceType("product.ProductService", [
    { name: "GetProductsByQuery", options: {}, I: CommonQuery, O: ProductDataSourceResponse },
    { name: "GetProductDetail", options: {}, I: GetBySlugRequest, O: ProductResponseWrapped },
    { name: "GetProductsByProductGroupSlug", options: {}, I: GetBySlugPagedRequest, O: ProductDataSourceResponse },
    { name: "GetProductGroupsBySlug", options: {}, I: GetBySlugRequest, O: ProductGroupResponseWrapped },
    { name: "GetProductGroupsByQuery", options: {}, I: CommonQuery, O: ProductGroupDataSourceResponse }
]);
