// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/seo.proto" (package "seo", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { SeoService } from "./seo";
import type { SitemapDataResponse } from "./seo";
import type { GetSitemapDataRequest } from "./seo";
import type { SeoPageConfigResponse } from "./seo";
import type { GetMetaByUrlRequest } from "./seo";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SeoGlobalConfigResponse } from "./seo";
import type { Empty } from "./common";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service seo.SeoService
 */
export interface ISeoServiceClient {
    /**
     * Global Config
     *
     * @generated from protobuf rpc: GetGlobalConfig
     */
    getGlobalConfig(input: Empty, options?: RpcOptions): UnaryCall<Empty, SeoGlobalConfigResponse>;
    /**
     * Page Config (merged)
     *
     * @generated from protobuf rpc: GetMetaByUrl
     */
    getMetaByUrl(input: GetMetaByUrlRequest, options?: RpcOptions): UnaryCall<GetMetaByUrlRequest, SeoPageConfigResponse>;
    /**
     * Sitemap Data
     *
     * @generated from protobuf rpc: GetSitemapData
     */
    getSitemapData(input: GetSitemapDataRequest, options?: RpcOptions): UnaryCall<GetSitemapDataRequest, SitemapDataResponse>;
}
/**
 * @generated from protobuf service seo.SeoService
 */
export class SeoServiceClient implements ISeoServiceClient, ServiceInfo {
    typeName = SeoService.typeName;
    methods = SeoService.methods;
    options = SeoService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Global Config
     *
     * @generated from protobuf rpc: GetGlobalConfig
     */
    getGlobalConfig(input: Empty, options?: RpcOptions): UnaryCall<Empty, SeoGlobalConfigResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, SeoGlobalConfigResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Page Config (merged)
     *
     * @generated from protobuf rpc: GetMetaByUrl
     */
    getMetaByUrl(input: GetMetaByUrlRequest, options?: RpcOptions): UnaryCall<GetMetaByUrlRequest, SeoPageConfigResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMetaByUrlRequest, SeoPageConfigResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Sitemap Data
     *
     * @generated from protobuf rpc: GetSitemapData
     */
    getSitemapData(input: GetSitemapDataRequest, options?: RpcOptions): UnaryCall<GetSitemapDataRequest, SitemapDataResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSitemapDataRequest, SitemapDataResponse>("unary", this._transport, method, opt, input);
    }
}
