// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/seo.proto" (package "seo", syntax proto3)
// tslint:disable
import { Empty } from "./common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message seo.GetMetaByUrlRequest
 */
export interface GetMetaByUrlRequest {
    /**
     * @generated from protobuf field: string url = 1
     */
    url: string;
}
/**
 * @generated from protobuf message seo.GetSitemapDataRequest
 */
export interface GetSitemapDataRequest {
    /**
     * @generated from protobuf field: string url = 1
     */
    url: string; // Base URL (e.g., https://optiflow.vn, https://optiflow.vn/api/sitemap?path={slug}.xml,...)
}
/**
 * @generated from protobuf message seo.SeoGlobalConfigResponse
 */
export interface SeoGlobalConfigResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: seo.SeoGlobalConfigData data = 3
     */
    data?: SeoGlobalConfigData;
}
/**
 * @generated from protobuf message seo.SeoPageConfigResponse
 */
export interface SeoPageConfigResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: seo.SeoPageConfigData data = 3
     */
    data?: SeoPageConfigData;
}
/**
 * @generated from protobuf message seo.SitemapDataResponse
 */
export interface SitemapDataResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: string xml_content = 3
     */
    xmlContent: string;
}
/**
 * Data Structures matching DTOs
 *
 * @generated from protobuf message seo.SeoGlobalConfigData
 */
export interface SeoGlobalConfigData {
    /**
     * @generated from protobuf field: string default_title = 1
     */
    defaultTitle: string;
    /**
     * @generated from protobuf field: string title_template = 2
     */
    titleTemplate: string;
    /**
     * @generated from protobuf field: string default_description = 3
     */
    defaultDescription: string;
    /**
     * @generated from protobuf field: string default_image = 4
     */
    defaultImage: string;
    /**
     * @generated from protobuf field: string robots_txt_content = 5
     */
    robotsTxtContent: string;
    /**
     * @generated from protobuf field: string google_site_verification_id = 6
     */
    googleSiteVerificationId: string;
    /**
     * @generated from protobuf field: map<string, string> social_links = 7
     */
    socialLinks: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: seo.SeoScriptsData scripts = 8
     */
    scripts?: SeoScriptsData;
    /**
     * @generated from protobuf field: string schema_markup = 9
     */
    schemaMarkup: string;
    /**
     * @generated from protobuf field: string locale = 10
     */
    locale: string;
    /**
     * @generated from protobuf field: string site_name = 11
     */
    siteName: string;
    /**
     * @generated from protobuf field: string domain = 12
     */
    domain: string;
    /**
     * @generated from protobuf field: string org_id = 13
     */
    orgId: string;
    /**
     * @generated from protobuf field: string description = 14
     */
    description: string;
    /**
     * @generated from protobuf field: seo.SeoAddressData address = 15
     */
    address?: SeoAddressData;
    /**
     * @generated from protobuf field: string founder = 16
     */
    founder: string;
    /**
     * @generated from protobuf field: string number_of_employees = 17
     */
    numberOfEmployees: string;
    /**
     * @generated from protobuf field: string brand_name = 18
     */
    brandName: string;
    /**
     * @generated from protobuf field: string geo_latitude = 19
     */
    geoLatitude: string;
    /**
     * @generated from protobuf field: string geo_longitude = 20
     */
    geoLongitude: string;
    /**
     * @generated from protobuf field: string google_maps_url = 21
     */
    googleMapsUrl: string;
    /**
     * @generated from protobuf field: repeated seo.SeoContactPointData contact_points = 22
     */
    contactPoints: SeoContactPointData[];
    /**
     * @generated from protobuf field: seo.SeoLogoData logo = 23
     */
    logo?: SeoLogoData;
    /**
     * @generated from protobuf field: seo.SeoOpenGraphData open_graph = 24
     */
    openGraph?: SeoOpenGraphData;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 25
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 26
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: string created_by = 27
     */
    createdBy: string;
    /**
     * @generated from protobuf field: string updated_by = 28
     */
    updatedBy: string;
    /**
     * @generated from protobuf field: string theme = 29
     */
    theme: string;
    /**
     * @generated from protobuf field: string layout = 30
     */
    layout: string;
}
/**
 * @generated from protobuf message seo.SeoScriptsData
 */
export interface SeoScriptsData {
    /**
     * @generated from protobuf field: string header = 1
     */
    header: string;
    /**
     * @generated from protobuf field: string body_start = 2
     */
    bodyStart: string;
    /**
     * @generated from protobuf field: string body_end = 3
     */
    bodyEnd: string;
}
/**
 * @generated from protobuf message seo.SeoPageConfigData
 */
export interface SeoPageConfigData {
    /**
     * @generated from protobuf field: string route = 1
     */
    route: string;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string;
    /**
     * @generated from protobuf field: string canonical_url = 4
     */
    canonicalUrl: string;
    /**
     * @generated from protobuf field: string schema_markup = 5
     */
    schemaMarkup: string;
    /**
     * @generated from protobuf field: bool is_amp_enabled = 6
     */
    isAmpEnabled: boolean;
    /**
     * @generated from protobuf field: seo.SeoRobotsMetaData robots = 7
     */
    robots?: SeoRobotsMetaData;
    /**
     * @generated from protobuf field: seo.SeoOpenGraphData open_graph = 8
     */
    openGraph?: SeoOpenGraphData;
    /**
     * @generated from protobuf field: seo.SeoSitemapConfigData sitemap = 9
     */
    sitemap?: SeoSitemapConfigData;
    /**
     * @generated from protobuf field: string entity_type = 10
     */
    entityType: string;
    /**
     * @generated from protobuf field: string entity_id = 11
     */
    entityId: string;
    /**
     * @generated from protobuf field: string org_id = 12
     */
    orgId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 13
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 14
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: string created_by = 15
     */
    createdBy: string;
    /**
     * @generated from protobuf field: string updated_by = 16
     */
    updatedBy: string;
    /**
     * @generated from protobuf field: repeated string keyword_list = 17
     */
    keywordList: string[];
}
/**
 * @generated from protobuf message seo.SeoRobotsMetaData
 */
export interface SeoRobotsMetaData {
    /**
     * @generated from protobuf field: bool index = 1
     */
    index: boolean;
    /**
     * @generated from protobuf field: bool follow = 2
     */
    follow: boolean;
    /**
     * @generated from protobuf field: int32 max_snippet = 3
     */
    maxSnippet: number;
    /**
     * @generated from protobuf field: string max_image_preview = 4
     */
    maxImagePreview: string;
    /**
     * @generated from protobuf field: int32 max_video_preview = 5
     */
    maxVideoPreview: number;
}
/**
 * @generated from protobuf message seo.SeoOpenGraphData
 */
export interface SeoOpenGraphData {
    /**
     * @generated from protobuf field: string title = 1
     */
    title: string;
    /**
     * @generated from protobuf field: string description = 2
     */
    description: string;
    /**
     * @generated from protobuf field: string image = 3
     */
    image: string;
    /**
     * @generated from protobuf field: string type = 4
     */
    type: string;
    /**
     * @generated from protobuf field: string locale = 5
     */
    locale: string;
    /**
     * @generated from protobuf field: string site_name = 6
     */
    siteName: string;
    /**
     * @generated from protobuf field: string url = 7
     */
    url: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_time = 8
     */
    updatedTime?: Timestamp;
}
/**
 * @generated from protobuf message seo.SeoSitemapConfigData
 */
export interface SeoSitemapConfigData {
    /**
     * @generated from protobuf field: bool include = 1
     */
    include: boolean;
    /**
     * @generated from protobuf field: string change_freq = 3
     */
    changeFreq: string;
}
/**
 * @generated from protobuf message seo.SeoAddressData
 */
export interface SeoAddressData {
    /**
     * @generated from protobuf field: string street_address = 1
     */
    streetAddress: string;
    /**
     * @generated from protobuf field: string address_region = 2
     */
    addressRegion: string;
    /**
     * @generated from protobuf field: string postal_code = 3
     */
    postalCode: string;
    /**
     * @generated from protobuf field: string address_country = 4
     */
    addressCountry: string;
}
/**
 * @generated from protobuf message seo.SeoContactPointData
 */
export interface SeoContactPointData {
    /**
     * @generated from protobuf field: string telephone = 1
     */
    telephone: string;
    /**
     * @generated from protobuf field: string contact_type = 2
     */
    contactType: string;
    /**
     * @generated from protobuf field: string email = 3
     */
    email: string;
    /**
     * @generated from protobuf field: string area_served = 4
     */
    areaServed: string;
}
/**
 * @generated from protobuf message seo.SeoLogoData
 */
export interface SeoLogoData {
    /**
     * @generated from protobuf field: string url = 1
     */
    url: string;
    /**
     * @generated from protobuf field: string caption = 2
     */
    caption: string;
    /**
     * @generated from protobuf field: string width = 3
     */
    width: string;
    /**
     * @generated from protobuf field: string height = 4
     */
    height: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetMetaByUrlRequest$Type extends MessageType<GetMetaByUrlRequest> {
    constructor() {
        super("seo.GetMetaByUrlRequest", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetMetaByUrlRequest>): GetMetaByUrlRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.url = "";
        if (value !== undefined)
            reflectionMergePartial<GetMetaByUrlRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMetaByUrlRequest): GetMetaByUrlRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string url */ 1:
                    message.url = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMetaByUrlRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string url = 1; */
        if (message.url !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.url);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.GetMetaByUrlRequest
 */
export const GetMetaByUrlRequest = new GetMetaByUrlRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSitemapDataRequest$Type extends MessageType<GetSitemapDataRequest> {
    constructor() {
        super("seo.GetSitemapDataRequest", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetSitemapDataRequest>): GetSitemapDataRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.url = "";
        if (value !== undefined)
            reflectionMergePartial<GetSitemapDataRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetSitemapDataRequest): GetSitemapDataRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string url */ 1:
                    message.url = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetSitemapDataRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string url = 1; */
        if (message.url !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.url);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.GetSitemapDataRequest
 */
export const GetSitemapDataRequest = new GetSitemapDataRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SeoGlobalConfigResponse$Type extends MessageType<SeoGlobalConfigResponse> {
    constructor() {
        super("seo.SeoGlobalConfigResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "message", T: () => SeoGlobalConfigData }
        ]);
    }
    create(value?: PartialMessage<SeoGlobalConfigResponse>): SeoGlobalConfigResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<SeoGlobalConfigResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SeoGlobalConfigResponse): SeoGlobalConfigResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* seo.SeoGlobalConfigData data */ 3:
                    message.data = SeoGlobalConfigData.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SeoGlobalConfigResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* seo.SeoGlobalConfigData data = 3; */
        if (message.data)
            SeoGlobalConfigData.internalBinaryWrite(message.data, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.SeoGlobalConfigResponse
 */
export const SeoGlobalConfigResponse = new SeoGlobalConfigResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SeoPageConfigResponse$Type extends MessageType<SeoPageConfigResponse> {
    constructor() {
        super("seo.SeoPageConfigResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "message", T: () => SeoPageConfigData }
        ]);
    }
    create(value?: PartialMessage<SeoPageConfigResponse>): SeoPageConfigResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<SeoPageConfigResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SeoPageConfigResponse): SeoPageConfigResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* seo.SeoPageConfigData data */ 3:
                    message.data = SeoPageConfigData.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SeoPageConfigResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* seo.SeoPageConfigData data = 3; */
        if (message.data)
            SeoPageConfigData.internalBinaryWrite(message.data, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.SeoPageConfigResponse
 */
export const SeoPageConfigResponse = new SeoPageConfigResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SitemapDataResponse$Type extends MessageType<SitemapDataResponse> {
    constructor() {
        super("seo.SitemapDataResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "xml_content", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SitemapDataResponse>): SitemapDataResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        message.xmlContent = "";
        if (value !== undefined)
            reflectionMergePartial<SitemapDataResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SitemapDataResponse): SitemapDataResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* string xml_content */ 3:
                    message.xmlContent = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SitemapDataResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* string xml_content = 3; */
        if (message.xmlContent !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.xmlContent);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.SitemapDataResponse
 */
export const SitemapDataResponse = new SitemapDataResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SeoGlobalConfigData$Type extends MessageType<SeoGlobalConfigData> {
    constructor() {
        super("seo.SeoGlobalConfigData", [
            { no: 1, name: "default_title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title_template", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "default_description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "default_image", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "robots_txt_content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "google_site_verification_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "social_links", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 8, name: "scripts", kind: "message", T: () => SeoScriptsData },
            { no: 9, name: "schema_markup", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "locale", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "site_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "domain", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "org_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "address", kind: "message", T: () => SeoAddressData },
            { no: 16, name: "founder", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "number_of_employees", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "brand_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "geo_latitude", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 20, name: "geo_longitude", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 21, name: "google_maps_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 22, name: "contact_points", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => SeoContactPointData },
            { no: 23, name: "logo", kind: "message", T: () => SeoLogoData },
            { no: 24, name: "open_graph", kind: "message", T: () => SeoOpenGraphData },
            { no: 25, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 26, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 27, name: "created_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 28, name: "updated_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 29, name: "theme", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 30, name: "layout", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SeoGlobalConfigData>): SeoGlobalConfigData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.defaultTitle = "";
        message.titleTemplate = "";
        message.defaultDescription = "";
        message.defaultImage = "";
        message.robotsTxtContent = "";
        message.googleSiteVerificationId = "";
        message.socialLinks = {};
        message.schemaMarkup = "";
        message.locale = "";
        message.siteName = "";
        message.domain = "";
        message.orgId = "";
        message.description = "";
        message.founder = "";
        message.numberOfEmployees = "";
        message.brandName = "";
        message.geoLatitude = "";
        message.geoLongitude = "";
        message.googleMapsUrl = "";
        message.contactPoints = [];
        message.createdBy = "";
        message.updatedBy = "";
        message.theme = "";
        message.layout = "";
        if (value !== undefined)
            reflectionMergePartial<SeoGlobalConfigData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SeoGlobalConfigData): SeoGlobalConfigData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string default_title */ 1:
                    message.defaultTitle = reader.string();
                    break;
                case /* string title_template */ 2:
                    message.titleTemplate = reader.string();
                    break;
                case /* string default_description */ 3:
                    message.defaultDescription = reader.string();
                    break;
                case /* string default_image */ 4:
                    message.defaultImage = reader.string();
                    break;
                case /* string robots_txt_content */ 5:
                    message.robotsTxtContent = reader.string();
                    break;
                case /* string google_site_verification_id */ 6:
                    message.googleSiteVerificationId = reader.string();
                    break;
                case /* map<string, string> social_links */ 7:
                    this.binaryReadMap7(message.socialLinks, reader, options);
                    break;
                case /* seo.SeoScriptsData scripts */ 8:
                    message.scripts = SeoScriptsData.internalBinaryRead(reader, reader.uint32(), options, message.scripts);
                    break;
                case /* string schema_markup */ 9:
                    message.schemaMarkup = reader.string();
                    break;
                case /* string locale */ 10:
                    message.locale = reader.string();
                    break;
                case /* string site_name */ 11:
                    message.siteName = reader.string();
                    break;
                case /* string domain */ 12:
                    message.domain = reader.string();
                    break;
                case /* string org_id */ 13:
                    message.orgId = reader.string();
                    break;
                case /* string description */ 14:
                    message.description = reader.string();
                    break;
                case /* seo.SeoAddressData address */ 15:
                    message.address = SeoAddressData.internalBinaryRead(reader, reader.uint32(), options, message.address);
                    break;
                case /* string founder */ 16:
                    message.founder = reader.string();
                    break;
                case /* string number_of_employees */ 17:
                    message.numberOfEmployees = reader.string();
                    break;
                case /* string brand_name */ 18:
                    message.brandName = reader.string();
                    break;
                case /* string geo_latitude */ 19:
                    message.geoLatitude = reader.string();
                    break;
                case /* string geo_longitude */ 20:
                    message.geoLongitude = reader.string();
                    break;
                case /* string google_maps_url */ 21:
                    message.googleMapsUrl = reader.string();
                    break;
                case /* repeated seo.SeoContactPointData contact_points */ 22:
                    message.contactPoints.push(SeoContactPointData.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* seo.SeoLogoData logo */ 23:
                    message.logo = SeoLogoData.internalBinaryRead(reader, reader.uint32(), options, message.logo);
                    break;
                case /* seo.SeoOpenGraphData open_graph */ 24:
                    message.openGraph = SeoOpenGraphData.internalBinaryRead(reader, reader.uint32(), options, message.openGraph);
                    break;
                case /* google.protobuf.Timestamp created_at */ 25:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 26:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* string created_by */ 27:
                    message.createdBy = reader.string();
                    break;
                case /* string updated_by */ 28:
                    message.updatedBy = reader.string();
                    break;
                case /* string theme */ 29:
                    message.theme = reader.string();
                    break;
                case /* string layout */ 30:
                    message.layout = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap7(map: SeoGlobalConfigData["socialLinks"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof SeoGlobalConfigData["socialLinks"] | undefined, val: SeoGlobalConfigData["socialLinks"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for seo.SeoGlobalConfigData.social_links");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: SeoGlobalConfigData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string default_title = 1; */
        if (message.defaultTitle !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.defaultTitle);
        /* string title_template = 2; */
        if (message.titleTemplate !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.titleTemplate);
        /* string default_description = 3; */
        if (message.defaultDescription !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.defaultDescription);
        /* string default_image = 4; */
        if (message.defaultImage !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.defaultImage);
        /* string robots_txt_content = 5; */
        if (message.robotsTxtContent !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.robotsTxtContent);
        /* string google_site_verification_id = 6; */
        if (message.googleSiteVerificationId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.googleSiteVerificationId);
        /* map<string, string> social_links = 7; */
        for (let k of globalThis.Object.keys(message.socialLinks))
            writer.tag(7, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.socialLinks[k]).join();
        /* seo.SeoScriptsData scripts = 8; */
        if (message.scripts)
            SeoScriptsData.internalBinaryWrite(message.scripts, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* string schema_markup = 9; */
        if (message.schemaMarkup !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.schemaMarkup);
        /* string locale = 10; */
        if (message.locale !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.locale);
        /* string site_name = 11; */
        if (message.siteName !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.siteName);
        /* string domain = 12; */
        if (message.domain !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.domain);
        /* string org_id = 13; */
        if (message.orgId !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.orgId);
        /* string description = 14; */
        if (message.description !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.description);
        /* seo.SeoAddressData address = 15; */
        if (message.address)
            SeoAddressData.internalBinaryWrite(message.address, writer.tag(15, WireType.LengthDelimited).fork(), options).join();
        /* string founder = 16; */
        if (message.founder !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.founder);
        /* string number_of_employees = 17; */
        if (message.numberOfEmployees !== "")
            writer.tag(17, WireType.LengthDelimited).string(message.numberOfEmployees);
        /* string brand_name = 18; */
        if (message.brandName !== "")
            writer.tag(18, WireType.LengthDelimited).string(message.brandName);
        /* string geo_latitude = 19; */
        if (message.geoLatitude !== "")
            writer.tag(19, WireType.LengthDelimited).string(message.geoLatitude);
        /* string geo_longitude = 20; */
        if (message.geoLongitude !== "")
            writer.tag(20, WireType.LengthDelimited).string(message.geoLongitude);
        /* string google_maps_url = 21; */
        if (message.googleMapsUrl !== "")
            writer.tag(21, WireType.LengthDelimited).string(message.googleMapsUrl);
        /* repeated seo.SeoContactPointData contact_points = 22; */
        for (let i = 0; i < message.contactPoints.length; i++)
            SeoContactPointData.internalBinaryWrite(message.contactPoints[i], writer.tag(22, WireType.LengthDelimited).fork(), options).join();
        /* seo.SeoLogoData logo = 23; */
        if (message.logo)
            SeoLogoData.internalBinaryWrite(message.logo, writer.tag(23, WireType.LengthDelimited).fork(), options).join();
        /* seo.SeoOpenGraphData open_graph = 24; */
        if (message.openGraph)
            SeoOpenGraphData.internalBinaryWrite(message.openGraph, writer.tag(24, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp created_at = 25; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(25, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 26; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(26, WireType.LengthDelimited).fork(), options).join();
        /* string created_by = 27; */
        if (message.createdBy !== "")
            writer.tag(27, WireType.LengthDelimited).string(message.createdBy);
        /* string updated_by = 28; */
        if (message.updatedBy !== "")
            writer.tag(28, WireType.LengthDelimited).string(message.updatedBy);
        /* string theme = 29; */
        if (message.theme !== "")
            writer.tag(29, WireType.LengthDelimited).string(message.theme);
        /* string layout = 30; */
        if (message.layout !== "")
            writer.tag(30, WireType.LengthDelimited).string(message.layout);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.SeoGlobalConfigData
 */
export const SeoGlobalConfigData = new SeoGlobalConfigData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SeoScriptsData$Type extends MessageType<SeoScriptsData> {
    constructor() {
        super("seo.SeoScriptsData", [
            { no: 1, name: "header", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "body_start", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "body_end", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SeoScriptsData>): SeoScriptsData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.header = "";
        message.bodyStart = "";
        message.bodyEnd = "";
        if (value !== undefined)
            reflectionMergePartial<SeoScriptsData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SeoScriptsData): SeoScriptsData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string header */ 1:
                    message.header = reader.string();
                    break;
                case /* string body_start */ 2:
                    message.bodyStart = reader.string();
                    break;
                case /* string body_end */ 3:
                    message.bodyEnd = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SeoScriptsData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string header = 1; */
        if (message.header !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.header);
        /* string body_start = 2; */
        if (message.bodyStart !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.bodyStart);
        /* string body_end = 3; */
        if (message.bodyEnd !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.bodyEnd);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.SeoScriptsData
 */
export const SeoScriptsData = new SeoScriptsData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SeoPageConfigData$Type extends MessageType<SeoPageConfigData> {
    constructor() {
        super("seo.SeoPageConfigData", [
            { no: 1, name: "route", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "canonical_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "schema_markup", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "is_amp_enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "robots", kind: "message", T: () => SeoRobotsMetaData },
            { no: 8, name: "open_graph", kind: "message", T: () => SeoOpenGraphData },
            { no: 9, name: "sitemap", kind: "message", T: () => SeoSitemapConfigData },
            { no: 10, name: "entity_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "entity_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "org_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 14, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 15, name: "created_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "updated_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "keyword_list", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SeoPageConfigData>): SeoPageConfigData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.route = "";
        message.title = "";
        message.description = "";
        message.canonicalUrl = "";
        message.schemaMarkup = "";
        message.isAmpEnabled = false;
        message.entityType = "";
        message.entityId = "";
        message.orgId = "";
        message.createdBy = "";
        message.updatedBy = "";
        message.keywordList = [];
        if (value !== undefined)
            reflectionMergePartial<SeoPageConfigData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SeoPageConfigData): SeoPageConfigData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string route */ 1:
                    message.route = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* string canonical_url */ 4:
                    message.canonicalUrl = reader.string();
                    break;
                case /* string schema_markup */ 5:
                    message.schemaMarkup = reader.string();
                    break;
                case /* bool is_amp_enabled */ 6:
                    message.isAmpEnabled = reader.bool();
                    break;
                case /* seo.SeoRobotsMetaData robots */ 7:
                    message.robots = SeoRobotsMetaData.internalBinaryRead(reader, reader.uint32(), options, message.robots);
                    break;
                case /* seo.SeoOpenGraphData open_graph */ 8:
                    message.openGraph = SeoOpenGraphData.internalBinaryRead(reader, reader.uint32(), options, message.openGraph);
                    break;
                case /* seo.SeoSitemapConfigData sitemap */ 9:
                    message.sitemap = SeoSitemapConfigData.internalBinaryRead(reader, reader.uint32(), options, message.sitemap);
                    break;
                case /* string entity_type */ 10:
                    message.entityType = reader.string();
                    break;
                case /* string entity_id */ 11:
                    message.entityId = reader.string();
                    break;
                case /* string org_id */ 12:
                    message.orgId = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 13:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 14:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* string created_by */ 15:
                    message.createdBy = reader.string();
                    break;
                case /* string updated_by */ 16:
                    message.updatedBy = reader.string();
                    break;
                case /* repeated string keyword_list */ 17:
                    message.keywordList.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SeoPageConfigData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string route = 1; */
        if (message.route !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.route);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* string canonical_url = 4; */
        if (message.canonicalUrl !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.canonicalUrl);
        /* string schema_markup = 5; */
        if (message.schemaMarkup !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.schemaMarkup);
        /* bool is_amp_enabled = 6; */
        if (message.isAmpEnabled !== false)
            writer.tag(6, WireType.Varint).bool(message.isAmpEnabled);
        /* seo.SeoRobotsMetaData robots = 7; */
        if (message.robots)
            SeoRobotsMetaData.internalBinaryWrite(message.robots, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* seo.SeoOpenGraphData open_graph = 8; */
        if (message.openGraph)
            SeoOpenGraphData.internalBinaryWrite(message.openGraph, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* seo.SeoSitemapConfigData sitemap = 9; */
        if (message.sitemap)
            SeoSitemapConfigData.internalBinaryWrite(message.sitemap, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* string entity_type = 10; */
        if (message.entityType !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.entityType);
        /* string entity_id = 11; */
        if (message.entityId !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.entityId);
        /* string org_id = 12; */
        if (message.orgId !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.orgId);
        /* google.protobuf.Timestamp created_at = 13; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 14; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(14, WireType.LengthDelimited).fork(), options).join();
        /* string created_by = 15; */
        if (message.createdBy !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.createdBy);
        /* string updated_by = 16; */
        if (message.updatedBy !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.updatedBy);
        /* repeated string keyword_list = 17; */
        for (let i = 0; i < message.keywordList.length; i++)
            writer.tag(17, WireType.LengthDelimited).string(message.keywordList[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.SeoPageConfigData
 */
export const SeoPageConfigData = new SeoPageConfigData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SeoRobotsMetaData$Type extends MessageType<SeoRobotsMetaData> {
    constructor() {
        super("seo.SeoRobotsMetaData", [
            { no: 1, name: "index", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "follow", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "max_snippet", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "max_image_preview", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "max_video_preview", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SeoRobotsMetaData>): SeoRobotsMetaData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.index = false;
        message.follow = false;
        message.maxSnippet = 0;
        message.maxImagePreview = "";
        message.maxVideoPreview = 0;
        if (value !== undefined)
            reflectionMergePartial<SeoRobotsMetaData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SeoRobotsMetaData): SeoRobotsMetaData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool index */ 1:
                    message.index = reader.bool();
                    break;
                case /* bool follow */ 2:
                    message.follow = reader.bool();
                    break;
                case /* int32 max_snippet */ 3:
                    message.maxSnippet = reader.int32();
                    break;
                case /* string max_image_preview */ 4:
                    message.maxImagePreview = reader.string();
                    break;
                case /* int32 max_video_preview */ 5:
                    message.maxVideoPreview = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SeoRobotsMetaData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool index = 1; */
        if (message.index !== false)
            writer.tag(1, WireType.Varint).bool(message.index);
        /* bool follow = 2; */
        if (message.follow !== false)
            writer.tag(2, WireType.Varint).bool(message.follow);
        /* int32 max_snippet = 3; */
        if (message.maxSnippet !== 0)
            writer.tag(3, WireType.Varint).int32(message.maxSnippet);
        /* string max_image_preview = 4; */
        if (message.maxImagePreview !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.maxImagePreview);
        /* int32 max_video_preview = 5; */
        if (message.maxVideoPreview !== 0)
            writer.tag(5, WireType.Varint).int32(message.maxVideoPreview);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.SeoRobotsMetaData
 */
export const SeoRobotsMetaData = new SeoRobotsMetaData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SeoOpenGraphData$Type extends MessageType<SeoOpenGraphData> {
    constructor() {
        super("seo.SeoOpenGraphData", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "image", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "locale", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "site_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "updated_time", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<SeoOpenGraphData>): SeoOpenGraphData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.description = "";
        message.image = "";
        message.type = "";
        message.locale = "";
        message.siteName = "";
        message.url = "";
        if (value !== undefined)
            reflectionMergePartial<SeoOpenGraphData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SeoOpenGraphData): SeoOpenGraphData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* string description */ 2:
                    message.description = reader.string();
                    break;
                case /* string image */ 3:
                    message.image = reader.string();
                    break;
                case /* string type */ 4:
                    message.type = reader.string();
                    break;
                case /* string locale */ 5:
                    message.locale = reader.string();
                    break;
                case /* string site_name */ 6:
                    message.siteName = reader.string();
                    break;
                case /* string url */ 7:
                    message.url = reader.string();
                    break;
                case /* google.protobuf.Timestamp updated_time */ 8:
                    message.updatedTime = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedTime);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SeoOpenGraphData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* string description = 2; */
        if (message.description !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.description);
        /* string image = 3; */
        if (message.image !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.image);
        /* string type = 4; */
        if (message.type !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.type);
        /* string locale = 5; */
        if (message.locale !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.locale);
        /* string site_name = 6; */
        if (message.siteName !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.siteName);
        /* string url = 7; */
        if (message.url !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.url);
        /* google.protobuf.Timestamp updated_time = 8; */
        if (message.updatedTime)
            Timestamp.internalBinaryWrite(message.updatedTime, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.SeoOpenGraphData
 */
export const SeoOpenGraphData = new SeoOpenGraphData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SeoSitemapConfigData$Type extends MessageType<SeoSitemapConfigData> {
    constructor() {
        super("seo.SeoSitemapConfigData", [
            { no: 1, name: "include", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "change_freq", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SeoSitemapConfigData>): SeoSitemapConfigData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.include = false;
        message.changeFreq = "";
        if (value !== undefined)
            reflectionMergePartial<SeoSitemapConfigData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SeoSitemapConfigData): SeoSitemapConfigData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool include */ 1:
                    message.include = reader.bool();
                    break;
                case /* string change_freq */ 3:
                    message.changeFreq = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SeoSitemapConfigData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool include = 1; */
        if (message.include !== false)
            writer.tag(1, WireType.Varint).bool(message.include);
        /* string change_freq = 3; */
        if (message.changeFreq !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.changeFreq);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.SeoSitemapConfigData
 */
export const SeoSitemapConfigData = new SeoSitemapConfigData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SeoAddressData$Type extends MessageType<SeoAddressData> {
    constructor() {
        super("seo.SeoAddressData", [
            { no: 1, name: "street_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "address_region", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "postal_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "address_country", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SeoAddressData>): SeoAddressData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.streetAddress = "";
        message.addressRegion = "";
        message.postalCode = "";
        message.addressCountry = "";
        if (value !== undefined)
            reflectionMergePartial<SeoAddressData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SeoAddressData): SeoAddressData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string street_address */ 1:
                    message.streetAddress = reader.string();
                    break;
                case /* string address_region */ 2:
                    message.addressRegion = reader.string();
                    break;
                case /* string postal_code */ 3:
                    message.postalCode = reader.string();
                    break;
                case /* string address_country */ 4:
                    message.addressCountry = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SeoAddressData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string street_address = 1; */
        if (message.streetAddress !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.streetAddress);
        /* string address_region = 2; */
        if (message.addressRegion !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.addressRegion);
        /* string postal_code = 3; */
        if (message.postalCode !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.postalCode);
        /* string address_country = 4; */
        if (message.addressCountry !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.addressCountry);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.SeoAddressData
 */
export const SeoAddressData = new SeoAddressData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SeoContactPointData$Type extends MessageType<SeoContactPointData> {
    constructor() {
        super("seo.SeoContactPointData", [
            { no: 1, name: "telephone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "contact_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "area_served", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SeoContactPointData>): SeoContactPointData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.telephone = "";
        message.contactType = "";
        message.email = "";
        message.areaServed = "";
        if (value !== undefined)
            reflectionMergePartial<SeoContactPointData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SeoContactPointData): SeoContactPointData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string telephone */ 1:
                    message.telephone = reader.string();
                    break;
                case /* string contact_type */ 2:
                    message.contactType = reader.string();
                    break;
                case /* string email */ 3:
                    message.email = reader.string();
                    break;
                case /* string area_served */ 4:
                    message.areaServed = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SeoContactPointData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string telephone = 1; */
        if (message.telephone !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.telephone);
        /* string contact_type = 2; */
        if (message.contactType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.contactType);
        /* string email = 3; */
        if (message.email !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.email);
        /* string area_served = 4; */
        if (message.areaServed !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.areaServed);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.SeoContactPointData
 */
export const SeoContactPointData = new SeoContactPointData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SeoLogoData$Type extends MessageType<SeoLogoData> {
    constructor() {
        super("seo.SeoLogoData", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "caption", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "width", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "height", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SeoLogoData>): SeoLogoData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.url = "";
        message.caption = "";
        message.width = "";
        message.height = "";
        if (value !== undefined)
            reflectionMergePartial<SeoLogoData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SeoLogoData): SeoLogoData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string url */ 1:
                    message.url = reader.string();
                    break;
                case /* string caption */ 2:
                    message.caption = reader.string();
                    break;
                case /* string width */ 3:
                    message.width = reader.string();
                    break;
                case /* string height */ 4:
                    message.height = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SeoLogoData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string url = 1; */
        if (message.url !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.url);
        /* string caption = 2; */
        if (message.caption !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.caption);
        /* string width = 3; */
        if (message.width !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.width);
        /* string height = 4; */
        if (message.height !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.height);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message seo.SeoLogoData
 */
export const SeoLogoData = new SeoLogoData$Type();
/**
 * @generated ServiceType for protobuf service seo.SeoService
 */
export const SeoService = new ServiceType("seo.SeoService", [
    { name: "GetGlobalConfig", options: {}, I: Empty, O: SeoGlobalConfigResponse },
    { name: "GetMetaByUrl", options: {}, I: GetMetaByUrlRequest, O: SeoPageConfigResponse },
    { name: "GetSitemapData", options: {}, I: GetSitemapDataRequest, O: SitemapDataResponse }
]);
