// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/tracking.proto" (package "tracking", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { TrackingService } from "./tracking";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { OperationResult } from "./common";
import type { UserEventRequest } from "./tracking";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service tracking.TrackingService
 */
export interface ITrackingServiceClient {
    /**
     * @generated from protobuf rpc: IngestEvent
     */
    ingestEvent(input: UserEventRequest, options?: RpcOptions): UnaryCall<UserEventRequest, OperationResult>;
}
/**
 * @generated from protobuf service tracking.TrackingService
 */
export class TrackingServiceClient implements ITrackingServiceClient, ServiceInfo {
    typeName = TrackingService.typeName;
    methods = TrackingService.methods;
    options = TrackingService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: IngestEvent
     */
    ingestEvent(input: UserEventRequest, options?: RpcOptions): UnaryCall<UserEventRequest, OperationResult> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserEventRequest, OperationResult>("unary", this._transport, method, opt, input);
    }
}
