// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/tracking.proto" (package "tracking", syntax proto3)
// tslint:disable
import { OperationResult } from "./common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message tracking.UserEventRequest
 */
export interface UserEventRequest {
    /**
     * @generated from protobuf field: string url = 1
     */
    url: string;
    /**
     * @generated from protobuf field: string action = 2
     */
    action: string;
    /**
     * @generated from protobuf field: string element_id = 3
     */
    elementId: string;
    /**
     * @generated from protobuf field: string session_id = 4
     */
    sessionId: string;
    /**
     * @generated from protobuf field: string user_agent = 5
     */
    userAgent: string;
    /**
     * @generated from protobuf field: string ip_address = 6
     */
    ipAddress: string;
    /**
     * @generated from protobuf field: string referrer = 7
     */
    referrer: string;
    /**
     * @generated from protobuf field: string metadata_json = 8
     */
    metadataJson: string; // Metadata as JSON string for gRPC
}
// @generated message type with reflection information, may provide speed optimized methods
class UserEventRequest$Type extends MessageType<UserEventRequest> {
    constructor() {
        super("tracking.UserEventRequest", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "action", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "element_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "user_agent", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "ip_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "referrer", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "metadata_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UserEventRequest>): UserEventRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.url = "";
        message.action = "";
        message.elementId = "";
        message.sessionId = "";
        message.userAgent = "";
        message.ipAddress = "";
        message.referrer = "";
        message.metadataJson = "";
        if (value !== undefined)
            reflectionMergePartial<UserEventRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserEventRequest): UserEventRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string url */ 1:
                    message.url = reader.string();
                    break;
                case /* string action */ 2:
                    message.action = reader.string();
                    break;
                case /* string element_id */ 3:
                    message.elementId = reader.string();
                    break;
                case /* string session_id */ 4:
                    message.sessionId = reader.string();
                    break;
                case /* string user_agent */ 5:
                    message.userAgent = reader.string();
                    break;
                case /* string ip_address */ 6:
                    message.ipAddress = reader.string();
                    break;
                case /* string referrer */ 7:
                    message.referrer = reader.string();
                    break;
                case /* string metadata_json */ 8:
                    message.metadataJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserEventRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string url = 1; */
        if (message.url !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.url);
        /* string action = 2; */
        if (message.action !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.action);
        /* string element_id = 3; */
        if (message.elementId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.elementId);
        /* string session_id = 4; */
        if (message.sessionId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.sessionId);
        /* string user_agent = 5; */
        if (message.userAgent !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.userAgent);
        /* string ip_address = 6; */
        if (message.ipAddress !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.ipAddress);
        /* string referrer = 7; */
        if (message.referrer !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.referrer);
        /* string metadata_json = 8; */
        if (message.metadataJson !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.metadataJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tracking.UserEventRequest
 */
export const UserEventRequest = new UserEventRequest$Type();
/**
 * @generated ServiceType for protobuf service tracking.TrackingService
 */
export const TrackingService = new ServiceType("tracking.TrackingService", [
    { name: "IngestEvent", options: {}, I: UserEventRequest, O: OperationResult }
]);
