// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "Protos/user_submit.proto" (package "user_submit", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UserSubmitService } from "./user_submit";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SubmitResponse } from "./user_submit";
import type { SubmitRequest } from "./user_submit";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service user_submit.UserSubmitService
 */
export interface IUserSubmitServiceClient {
    /**
     * @generated from protobuf rpc: Submit
     */
    submit(input: SubmitRequest, options?: RpcOptions): UnaryCall<SubmitRequest, SubmitResponse>;
}
/**
 * @generated from protobuf service user_submit.UserSubmitService
 */
export class UserSubmitServiceClient implements IUserSubmitServiceClient, ServiceInfo {
    typeName = UserSubmitService.typeName;
    methods = UserSubmitService.methods;
    options = UserSubmitService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Submit
     */
    submit(input: SubmitRequest, options?: RpcOptions): UnaryCall<SubmitRequest, SubmitResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SubmitRequest, SubmitResponse>("unary", this._transport, method, opt, input);
    }
}
